---
title: "PDP_data_extract"
format: html
---
# RF
## - !sec! Partial dependence plots
### - Data extraction & export
```{r}
### PREDICTOR: VELOCITY ### -------------------------------------------------
# With k_index as response --------------------------------------------------
### velocity
pdp_model_v_k_c <- pdp::partial(rf_model_v_k_c, pred.var = "velocity")|>
  mutate(predictors = "velocity_c",
         model = "velocity w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_k_c, "ML_Model/pdp_data/pdp_v_k_c_rf.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
pdp_model_v_s_c <- pdp::partial(rf_model_v_s_c, pred.var = "velocity")|>
  mutate(predictors = "velocity_c",
         model = "velocity w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_v_s_c, "ML_Model/pdp_data/pdp_v_s_c_rf.csv", row.names = FALSE)

# With abundance as response --------------------------------------------------
### velocity 
pdp_model_v_a_c <- pdp::partial(rf_model_v_a_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "velocity w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_a_c, "ML_Model/pdp_data/pdp_v_a_c_rf.csv", row.names = FALSE)


# With rel_abundance as response ----------------------------------------------
### velocity 
pdp_model_v_ra_c <- pdp::partial(rf_model_v_ra_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "velocity w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_ra_c, "ML_Model/pdp_data/pdp_v_ra_c_rf.csv", row.names = FALSE)

### PREDICTORS: VELOCITY + WD ### --------------------------------------------
# With k_index as response ---------------------------------------------------
### velocity 
pdp_model_v_wd_k_c <- pdp::partial(rf_model_wd_k_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "v + wd w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_wd_k_c, "ML_Model/pdp_data/pdp_v_wd_k_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_k_c <- pdp::partial(rf_model_wd_k_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "v + wd w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_wd_k_c, "ML_Model/pdp_data/pdp_wd_k_c_rf.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
pdp_model_v_wd_s_c <- pdp::partial(rf_model_wd_s_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "v + wd w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_v_wd_s_c, "ML_Model/pdp_data/pdp_v_wd_s_c_rf.csv", row.names = FALSE)

### wd_m
pdp_model_wd_s_c <- pdp::partial(rf_model_wd_s_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "v + wd w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_wd_s_c, "ML_Model/pdp_data/pdp_wd_s_c_rf.csv", row.names = FALSE)

# With abundance as response --------------------------------------------------
### velocity 
pdp_model_v_wd_a_c <- pdp::partial(rf_model_wd_a_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "v + wd w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_wd_a_c, "ML_Model/pdp_data/pdp_v_wd_a_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_a_c <- pdp::partial(rf_model_wd_a_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "v + wd w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_wd_a_c, "ML_Model/pdp_data/pdp_wd_a_c_rf.csv", row.names = FALSE)

# With rel_abundance as response ---------------------------------------------
### velocity
pdp_model_v_wd_ra_c <- pdp::partial(rf_model_wd_ra_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "v + wd w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_wd_ra_c, "ML_Model/pdp_data/pdp_v_wd_ra_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_ra_c <- pdp::partial(rf_model_wd_ra_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "v + wd w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_wd_ra_c, "ML_Model/pdp_data/pdp_wd_ra_c_rf.csv", row.names = FALSE)

### PREDICTORS: SAMPLING LOCATIONS ### ---------------------------------------
# With k_index as response ---------------------------------------------------
### velocity 
pdp_model_v_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_samp_k_c, "ML_Model/pdp_data/pdp_v_samp_k_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_wd_samp_k_c, "ML_Model/pdp_data/pdp_wd_samp_k_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_z_samp_k_c, "ML_Model/pdp_data/pdp_z_samp_k_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_dist_samp_k_c, "ML_Model/pdp_data/pdp_dist_samp_k_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cv_samp_k_c, "ML_Model/pdp_data/pdp_cv_samp_k_c_rf.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ac_samp_k_c, "ML_Model/pdp_data/pdp_ac_samp_k_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_mc_samp_k_c, "ML_Model/pdp_data/pdp_mc_samp_k_c_rf.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cc_samp_k_c, "ML_Model/pdp_data/pdp_cc_samp_k_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_3_samp_k_c, "ML_Model/pdp_data/pdp_clog_3_samp_k_c_rf.csv", row.names = FALSE)

### clog_6 
pdp_model_clog_6_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_6_samp_k_c, "ML_Model/pdp_data/pdp_clog_6_samp_k_c_rf.csv", row.names = FALSE)

### sub_type
pdp_model_sub_samp_k_c <- pdp::partial(rf_model_samp_k_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_sub_samp_k_c, "ML_Model/pdp_data/pdp_sub_samp_k_c_rf.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
pdp_model_v_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_v_samp_s_c, "ML_Model/pdp_data/pdp_v_samp_s_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_wd_samp_s_c, "ML_Model/pdp_data/pdp_wd_samp_s_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_z_samp_s_c, "ML_Model/pdp_data/pdp_z_samp_s_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_dist_samp_s_c, "ML_Model/pdp_data/pdp_dist_samp_s_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/ coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cv_samp_s_c, "ML_Model/pdp_data/pdp_cv_samp_s_c_rf.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ac_samp_s_c, "ML_Model/pdp_data/pdp_ac_samp_s_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_mc_samp_s_c, "ML_Model/pdp_data/pdp_mc_samp_s_c_rf.csv", row.names = FALSE)

### cpom_cover
pdp_model_cc_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cc_samp_s_c, "ML_Model/pdp_data/pdp_cc_samp_s_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_3_samp_s_c, "ML_Model/pdp_data/pdp_clog_3_samp_s_c_rf.csv", row.names = FALSE)

### clog_6 
pdp_model_clog_6_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_6_samp_s_c, "ML_Model/pdp_data/pdp_clog_6_samp_s_c_rf.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_samp_s_c <- pdp::partial(rf_model_samp_s_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_sub_samp_s_c, "ML_Model/pdp_data/pdp_sub_samp_s_c_rf.csv", row.names = FALSE)

# With abundance as response --------------------------------------------------
### velocity 
pdp_model_v_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_samp_a_c, "ML_Model/pdp_data/pdp_v_samp_a_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_wd_samp_a_c, "ML_Model/pdp_data/pdp_wd_samp_a_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_z_samp_a_c, "ML_Model/pdp_data/pdp_z_samp_a_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_dist_samp_a_c, "ML_Model/pdp_data/pdp_dist_samp_a_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cv_samp_a_c, "ML_Model/pdp_data/pdp_cv_samp_a_c_rf.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ac_samp_a_c, "ML_Model/pdp_data/pdp_ac_samp_a_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_mc_samp_a_c, "ML_Model/pdp_data/pdp_mc_samp_a_c_rf.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cc_samp_a_c, "ML_Model/pdp_data/pdp_cc_samp_a_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_3_samp_a_c, "ML_Model/pdp_data/pdp_clog_3_samp_a_c_rf.csv", row.names = FALSE)

### clog_6 
pdp_model_clog_6_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_6_samp_a_c, "ML_Model/pdp_data/pdp_clog_6_samp_a_c_rf.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_samp_a_c <- pdp::partial(rf_model_samp_a_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_sub_samp_a_c, "ML_Model/pdp_data/pdp_sub_samp_a_c_rf.csv", row.names = FALSE)

# With rel_abundance as response ----------------------------------------------
### velocity 
pdp_model_v_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_samp_ra_c, "ML_Model/pdp_data/pdp_v_samp_ra_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_wd_samp_ra_c, "ML_Model/pdp_data/pdp_wd_samp_ra_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_z_samp_ra_c, "ML_Model/pdp_data/pdp_z_samp_ra_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_dist_samp_ra_c, "ML_Model/pdp_data/pdp_dist_samp_ra_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cv_samp_ra_c, "ML_Model/pdp_data/pdp_cv_samp_ra_c_rf.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ac_samp_ra_c, "ML_Model/pdp_data/pdp_ac_samp_ra_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_mc_samp_ra_c, "ML_Model/pdp_data/pdp_mc_samp_ra_c_rf.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cc_samp_ra_c, "ML_Model/pdp_data/pdp_cc_samp_ra_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_3_samp_ra_c, "ML_Model/pdp_data/pdp_clog_3_samp_ra_c_rf.csv", row.names = FALSE)

### clog_6 
pdp_model_clog_6_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_6_samp_ra_c, "ML_Model/pdp_data/pdp_clog_6_samp_ra_c_rf.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_samp_ra_c <- pdp::partial(rf_model_samp_ra_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_sub_samp_ra_c, "ML_Model/pdp_data/pdp_sub_samp_ra_c_rf.csv", row.names = FALSE)

### PREDICTORS: ALL PREDICTORS ### --------------------------------------------
# With k_index as response ----------------------------------------------------
### velocity 
pdp_model_v_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_sec_k_c, "ML_Model/pdp_data/pdp_v_sec_k_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_wd_sec_k_c, "ML_Model/pdp_data/pdp_wd_sec_k_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_z_sec_k_c, "ML_Model/pdp_data/pdp_z_sec_k_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_dist_sec_k_c, "ML_Model/pdp_data/pdp_dist_sec_k_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cv_sec_k_c, "ML_Model/pdp_data/pdp_cv_sec_k_c_rf.csv", row.names = FALSE)

### alg_cover
pdp_model_ac_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ac_sec_k_c, "ML_Model/pdp_data/pdp_ac_sec_k_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_mc_sec_k_c, "ML_Model/pdp_data/pdp_mc_sec_k_c_rf.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cc_sec_k_c, "ML_Model/pdp_data/pdp_cc_sec_k_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_3_sec_k_c, "ML_Model/pdp_data/pdp_clog_3_sec_k_c_rf.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_6_sec_k_c, "ML_Model/pdp_data/pdp_clog_6_sec_k_c_rf.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_sub_sec_k_c, "ML_Model/pdp_data/pdp_sub_sec_k_c_rf.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "pH_before") |>
  mutate(predictors = "pH_before",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_phb_sec_k_c, "ML_Model/pdp_data/pdp_phb_sec_k_c_rf.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "pH_during") |>
  mutate(predictors = "pH_during",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_phd_sec_k_c, "ML_Model/pdp_data/pdp_phd_sec_k_c_rf.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "pH_after") |>
  mutate(predictors = "pH_after",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_pha_sec_k_c, "ML_Model/pdp_data/pdp_pha_sec_k_c_rf.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "conduct_before") |>
  mutate(predictors = "conduct_before",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cb_sec_k_c, "ML_Model/pdp_data/pdp_cb_sec_k_c_rf.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "conduct_during") |>
  mutate(predictors = "conduct_during",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cd_sec_k_c, "ML_Model/pdp_data/pdp_cd_sec_k_c_rf.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "conduct_after") |>
  mutate(predictors = "conduct_after",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ca_sec_k_c, "ML_Model/pdp_data/pdp_ca_sec_k_c_rf.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "ox_before") |>
  mutate(predictors = "ox_before",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ob_sec_k_c, "ML_Model/pdp_data/pdp_ob_sec_k_c_rf.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "ox_during") |>
  mutate(predictors = "ox_during",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_od_sec_k_c, "ML_Model/pdp_data/pdp_od_sec_k_c_rf.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "ox_after") |>
  mutate(predictors = "ox_after",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_oa_sec_k_c, "ML_Model/pdp_data/pdp_oa_sec_k_c_rf.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "turb_before") |>
  mutate(predictors = "turb_before",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_tb_sec_k_c, "ML_Model/pdp_data/pdp_tb_sec_k_c_rf.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "turb_during") |>
  mutate(predictors = "turb_during",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_td_sec_k_c, "ML_Model/pdp_data/pdp_td_sec_k_c_rf.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "turb_after") |>
  mutate(predictors = "turb_after",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ta_sec_k_c, "ML_Model/pdp_data/pdp_ta_sec_k_c_rf.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "temp_before") |>
  mutate(predictors = "temp_before",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_teb_sec_k_c, "ML_Model/pdp_data/pdp_teb_sec_k_c_rf.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "temp_during") |>
  mutate(predictors = "temp_during",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ted_sec_k_c, "ML_Model/pdp_data/pdp_ted_sec_k_c_rf.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "temp_after") |>
  mutate(predictors = "temp_after",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_tea_sec_k_c, "ML_Model/pdp_data/pdp_tea_sec_k_c_rf.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "q_before") |>
  mutate(predictors = "q_before",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_qb_sec_k_c, "ML_Model/pdp_data/pdp_qb_sec_k_c_rf.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "q_during") |>
  mutate(predictors = "q_during",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_qd_sec_k_c, "ML_Model/pdp_data/pdp_qd_sec_k_c_rf.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "q_after") |>
  mutate(predictors = "q_after",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_qa_sec_k_c, "ML_Model/pdp_data/pdp_qa_sec_k_c_rf.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "gaug_before") |>
  mutate(predictors = "gaug_before",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_gb_sec_k_c, "ML_Model/pdp_data/pdp_gb_sec_k_c_rf.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "gaug_during") |>
  mutate(predictors = "gaug_during",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_gd_sec_k_c, "ML_Model/pdp_data/pdp_gd_sec_k_c_rf.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_k_c <- pdp::partial(rf_model_sec_k_c, pred.var = "gaug_after") |>
  mutate(predictors = "gaug_after",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ga_sec_k_c, "ML_Model/pdp_data/pdp_ga_sec_k_c_rf.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
pdp_model_v_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_v_sec_s_c, "ML_Model/pdp_data/pdp_v_sec_s_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_wd_sec_s_c, "ML_Model/pdp_data/pdp_wd_sec_s_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_z_sec_s_c, "ML_Model/pdp_data/pdp_z_sec_s_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_dist_sec_s_c, "ML_Model/pdp_data/pdp_dist_sec_s_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cv_sec_s_c, "ML_Model/pdp_data/pdp_cv_sec_s_c_rf.csv", row.names = FALSE)

### alg_cover
pdp_model_ac_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ac_sec_s_c, "ML_Model/pdp_data/pdp_ac_sec_s_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_mc_sec_s_c, "ML_Model/pdp_data/pdp_mc_sec_s_c_rf.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cc_sec_s_c, "ML_Model/pdp_data/pdp_cc_sec_s_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_3_sec_s_c, "ML_Model/pdp_data/pdp_clog_3_sec_s_c_rf.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_6_sec_s_c, "ML_Model/pdp_data/pdp_clog_6_sec_s_c_rf.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_sub_sec_s_c, "ML_Model/pdp_data/pdp_sub_sec_s_c_rf.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "pH_before") |>
  mutate(predictors = "pH_before",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_phb_sec_s_c, "ML_Model/pdp_data/pdp_phb_sec_s_c_rf.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "pH_during") |>
  mutate(predictors = "pH_during",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_phd_sec_s_c, "ML_Model/pdp_data/pdp_phd_sec_s_c_rf.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "pH_after") |>
  mutate(predictors = "pH_after",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_pha_sec_s_c, "ML_Model/pdp_data/pdp_pha_sec_s_c_rf.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "conduct_before") |>
  mutate(predictors = "conduct_before",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cb_sec_s_c, "ML_Model/pdp_data/pdp_cb_sec_s_c_rf.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "conduct_during") |>
  mutate(predictors = "conduct_during",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cd_sec_s_c, "ML_Model/pdp_data/pdp_cd_sec_s_c_rf.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "conduct_after") |>
  mutate(predictors = "conduct_after",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ca_sec_s_c, "ML_Model/pdp_data/pdp_ca_sec_s_c_rf.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "ox_before") |>
  mutate(predictors = "ox_before",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ob_sec_s_c, "ML_Model/pdp_data/pdp_ob_sec_s_c_rf.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "ox_during") |>
  mutate(predictors = "ox_during",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_od_sec_s_c, "ML_Model/pdp_data/pdp_od_sec_s_c_rf.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "ox_after") |>
  mutate(predictors = "ox_after",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_oa_sec_s_c, "ML_Model/pdp_data/pdp_oa_sec_s_c_rf.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "turb_before") |>
  mutate(predictors = "turb_before",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_tb_sec_s_c, "ML_Model/pdp_data/pdp_tb_sec_s_c_rf.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "turb_during") |>
  mutate(predictors = "turb_during",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_td_sec_s_c, "ML_Model/pdp_data/pdp_td_sec_s_c_rf.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "turb_after") |>
  mutate(predictors = "turb_after",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ta_sec_s_c, "ML_Model/pdp_data/pdp_ta_sec_s_c_rf.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "temp_before") |>
  mutate(predictors = "temp_before",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_teb_sec_s_c, "ML_Model/pdp_data/pdp_teb_sec_s_c_rf.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "temp_during") |>
  mutate(predictors = "temp_during",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ted_sec_s_c, "ML_Model/pdp_data/pdp_ted_sec_s_c_rf.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "temp_after") |>
  mutate(predictors = "temp_after",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_tea_sec_s_c, "ML_Model/pdp_data/pdp_tea_sec_s_c_rf.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "q_before") |>
  mutate(predictors = "q_before",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_qb_sec_s_c, "ML_Model/pdp_data/pdp_qb_sec_s_c_rf.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "q_during") |>
  mutate(predictors = "q_during",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_qd_sec_s_c, "ML_Model/pdp_data/pdp_qd_sec_s_c_rf.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "q_after") |>
  mutate(predictors = "q_after",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_qa_sec_s_c, "ML_Model/pdp_data/pdp_qa_sec_s_c_rf.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "gaug_before") |>
  mutate(predictors = "gaug_before",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_gb_sec_s_c, "ML_Model/pdp_data/pdp_gb_sec_s_c_rf.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "gaug_during") |>
  mutate(predictors = "gaug_during",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_gd_sec_s_c, "ML_Model/pdp_data/pdp_gd_sec_s_c_rf.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_s_c <- pdp::partial(rf_model_sec_s_c, pred.var = "gaug_after") |>
  mutate(predictors = "gaug_after",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ga_sec_s_c, "ML_Model/pdp_data/pdp_ga_sec_s_c_rf.csv", row.names = FALSE)

# With abundance as response --------------------------------------------------
### velocity 
pdp_model_v_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_sec_a_c, "ML_Model/pdp_data/pdp_v_sec_a_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_wd_sec_a_c, "ML_Model/pdp_data/pdp_wd_sec_a_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_z_sec_a_c, "ML_Model/pdp_data/pdp_z_sec_a_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_dist_sec_a_c, "ML_Model/pdp_data/pdp_dist_sec_a_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cv_sec_a_c, "ML_Model/pdp_data/pdp_cv_sec_a_c_rf.csv", row.names = FALSE)

### alg_cover
pdp_model_ac_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ac_sec_a_c, "ML_Model/pdp_data/pdp_ac_sec_a_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_mc_sec_a_c, "ML_Model/pdp_data/pdp_mc_sec_a_c_rf.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cc_sec_a_c, "ML_Model/pdp_data/pdp_cc_sec_a_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_3_sec_a_c, "ML_Model/pdp_data/pdp_clog_3_sec_a_c_rf.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_6_sec_a_c, "ML_Model/pdp_data/pdp_clog_6_sec_a_c_rf.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_sub_sec_a_c, "ML_Model/pdp_data/pdp_sub_sec_a_c_rf.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "pH_before") |>
  mutate(predictors = "pH_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_phb_sec_a_c, "ML_Model/pdp_data/pdp_phb_sec_a_c_rf.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "pH_during") |>
  mutate(predictors = "pH_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_phd_sec_a_c, "ML_Model/pdp_data/pdp_phd_sec_a_c_rf.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "pH_after") |>
  mutate(predictors = "pH_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_pha_sec_a_c, "ML_Model/pdp_data/pdp_pha_sec_a_c_rf.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "conduct_before") |>
  mutate(predictors = "conduct_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cb_sec_a_c, "ML_Model/pdp_data/pdp_cb_sec_a_c_rf.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "conduct_during") |>
  mutate(predictors = "conduct_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cd_sec_a_c, "ML_Model/pdp_data/pdp_cd_sec_a_c_rf.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "conduct_after") |>
  mutate(predictors = "conduct_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ca_sec_a_c, "ML_Model/pdp_data/pdp_ca_sec_a_c_rf.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "ox_before") |>
  mutate(predictors = "ox_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ob_sec_a_c, "ML_Model/pdp_data/pdp_ob_sec_a_c_rf.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "ox_during") |>
  mutate(predictors = "ox_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_od_sec_a_c, "ML_Model/pdp_data/pdp_od_sec_a_c_rf.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "ox_after") |>
  mutate(predictors = "ox_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_oa_sec_a_c, "ML_Model/pdp_data/pdp_oa_sec_a_c_rf.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "turb_before") |>
  mutate(predictors = "turb_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_tb_sec_a_c, "ML_Model/pdp_data/pdp_tb_sec_a_c_rf.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "turb_during") |>
  mutate(predictors = "turb_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_td_sec_a_c, "ML_Model/pdp_data/pdp_td_sec_a_c_rf.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "turb_after") |>
  mutate(predictors = "turb_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ta_sec_a_c, "ML_Model/pdp_data/pdp_ta_sec_a_c_rf.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "temp_before") |>
  mutate(predictors = "temp_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_teb_sec_a_c, "ML_Model/pdp_data/pdp_teb_sec_a_c_rf.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "temp_during") |>
  mutate(predictors = "temp_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ted_sec_a_c, "ML_Model/pdp_data/pdp_ted_sec_a_c_rf.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "temp_after") |>
  mutate(predictors = "temp_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_tea_sec_a_c, "ML_Model/pdp_data/pdp_tea_sec_a_c_rf.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "q_before") |>
  mutate(predictors = "q_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_qb_sec_a_c, "ML_Model/pdp_data/pdp_qb_sec_a_c_rf.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "q_during") |>
  mutate(predictors = "q_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_qd_sec_a_c, "ML_Model/pdp_data/pdp_qd_sec_a_c_rf.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "q_after") |>
  mutate(predictors = "q_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_qa_sec_a_c, "ML_Model/pdp_data/pdp_qa_sec_a_c_rf.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "gaug_before") |>
  mutate(predictors = "gaug_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_gb_sec_a_c, "ML_Model/pdp_data/pdp_gb_sec_a_c_rf.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "gaug_during") |>
  mutate(predictors = "gaug_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_gd_sec_a_c, "ML_Model/pdp_data/pdp_gd_sec_a_c_rf.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_a_c <- pdp::partial(rf_model_sec_a_c, pred.var = "gaug_after") |>
  mutate(predictors = "gaug_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ga_sec_a_c, "ML_Model/pdp_data/pdp_ga_sec_a_c_rf.csv", row.names = FALSE)

# With relative abundance as response -----------------------------------------
### velocity 
pdp_model_v_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_sec_ra_c, "ML_Model/pdp_data/pdp_v_sec_ra_c_rf.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_wd_sec_ra_c, "ML_Model/pdp_data/pdp_wd_sec_ra_c_rf.csv", row.names = FALSE)

### z 
pdp_model_z_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "z") |>
  mutate(predictors = "z",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_z_sec_ra_c, "ML_Model/pdp_data/pdp_z_sec_ra_c_rf.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "dist_w") |>
  mutate(predictors = "dist_w",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_dist_sec_ra_c, "ML_Model/pdp_data/pdp_dist_sec_ra_c_rf.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "cat_velocity") |>
  mutate(predictors = "cat_velocity",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cv_sec_ra_c, "ML_Model/pdp_data/pdp_cv_sec_ra_c_rf.csv", row.names = FALSE)

### alg_cover
pdp_model_ac_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "alg_cover") |>
  mutate(predictors = "alg_cover",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ac_sec_ra_c, "ML_Model/pdp_data/pdp_ac_sec_ra_c_rf.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "moos_cover") |>
  mutate(predictors = "moos_cover",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_mc_sec_ra_c, "ML_Model/pdp_data/pdp_mc_sec_ra_c_rf.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "cpom_cover") |>
  mutate(predictors = "cpom_cover",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cc_sec_ra_c, "ML_Model/pdp_data/pdp_cc_sec_ra_c_rf.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "clog_3_class_int") |>
  mutate(predictors = "clog_3_class",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_3_sec_ra_c, "ML_Model/pdp_data/pdp_clog_3_sec_ra_c_rf.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "clog_6_class_int") |>
  mutate(predictors = "clog_6_class",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_6_sec_ra_c, "ML_Model/pdp_data/pdp_clog_6_sec_ra_c_rf.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "sub_type_int") |>
  mutate(predictors = "sub_type",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_sub_sec_ra_c, "ML_Model/pdp_data/pdp_sub_sec_ra_c_rf.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "pH_before") |>
  mutate(predictors = "pH_before",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_phb_sec_ra_c, "ML_Model/pdp_data/pdp_phb_sec_ra_c_rf.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "pH_during") |>
  mutate(predictors = "pH_during",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_phd_sec_ra_c, "ML_Model/pdp_data/pdp_phd_sec_ra_c_rf.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "pH_after") |>
  mutate(predictors = "pH_after",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_pha_sec_ra_c, "ML_Model/pdp_data/pdp_pha_sec_ra_c_rf.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "conduct_before") |>
  mutate(predictors = "conduct_before",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cb_sec_ra_c, "ML_Model/pdp_data/pdp_cb_sec_ra_c_rf.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "conduct_during") |>
  mutate(predictors = "conduct_during",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cd_sec_ra_c, "ML_Model/pdp_data/pdp_cd_sec_ra_c_rf.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "conduct_after") |>
  mutate(predictors = "conduct_after",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ca_sec_ra_c, "ML_Model/pdp_data/pdp_ca_sec_ra_c_rf.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "ox_before") |>
  mutate(predictors = "ox_before",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ob_sec_ra_c, "ML_Model/pdp_data/pdp_ob_sec_ra_c_rf.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "ox_during") |>
  mutate(predictors = "ox_during",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_od_sec_ra_c, "ML_Model/pdp_data/pdp_od_sec_ra_c_rf.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "ox_after") |>
  mutate(predictors = "ox_after",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_oa_sec_ra_c, "ML_Model/pdp_data/pdp_oa_sec_ra_c_rf.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "turb_before") |>
  mutate(predictors = "turb_before",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_tb_sec_ra_c, "ML_Model/pdp_data/pdp_tb_sec_ra_c_rf.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "turb_during") |>
  mutate(predictors = "turb_during",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_td_sec_ra_c, "ML_Model/pdp_data/pdp_td_sec_ra_c_rf.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "turb_after") |>
  mutate(predictors = "turb_after",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ta_sec_ra_c, "ML_Model/pdp_data/pdp_ta_sec_ra_c_rf.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "temp_before") |>
  mutate(predictors = "temp_before",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_teb_sec_ra_c, "ML_Model/pdp_data/pdp_teb_sec_ra_c_rf.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "temp_during") |>
  mutate(predictors = "temp_during",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ted_sec_ra_c, "ML_Model/pdp_data/pdp_ted_sec_ra_c_rf.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "temp_after") |>
  mutate(predictors = "temp_after",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_tea_sec_ra_c, "ML_Model/pdp_data/pdp_tea_sec_ra_c_rf.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "q_before") |>
  mutate(predictors = "q_before",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_qb_sec_ra_c, "ML_Model/pdp_data/pdp_qb_sec_ra_c_rf.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "q_during") |>
  mutate(predictors = "q_during",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_qd_sec_ra_c, "ML_Model/pdp_data/pdp_qd_sec_ra_c_rf.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "q_after") |>
  mutate(predictors = "q_after",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_qa_sec_ra_c, "ML_Model/pdp_data/pdp_qa_sec_ra_c_rf.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "gaug_before") |>
  mutate(predictors = "gaug_before",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_gb_sec_ra_c, "ML_Model/pdp_data/pdp_gb_sec_ra_c_rf.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "gaug_during") |>
  mutate(predictors = "gaug_during",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_gd_sec_ra_c, "ML_Model/pdp_data/pdp_gd_sec_ra_c_rf.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_ra_c <- pdp::partial(rf_model_sec_ra_c, pred.var = "gaug_after") |>
  mutate(predictors = "gaug_after",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ga_sec_ra_c, "ML_Model/pdp_data/pdp_ga_sec_ra_c_rf.csv", row.names = FALSE)

### PREDICTOR: SELECTED VARIABLES ### -----------------------------------------
# With k_index as response --------------------------------------------------
### velocity
pdp_model_v_var_k_c <- pdp::partial(rf_model_var_k_c, pred.var = "velocity")|>
  mutate(predictors = "velocity",
         model = "velocity w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_var_k_c, "ML_Model/pdp_data/pdp_v_var_k_c_rf.csv", row.names = FALSE)

### z
pdp_model_z_var_k_c <- pdp::partial(rf_model_var_k_c, pred.var = "z")|>
  mutate(predictors = "z",
         model = "z w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_z_var_k_c, "ML_Model/pdp_data/pdp_z_var_k_c_rf.csv", row.names = FALSE)

### wd_m
pdp_model_wd_var_k_c <- pdp::partial(rf_model_var_k_c, pred.var = "wd_m")|>
  mutate(predictors = "wd_m",
         model = "wd_m w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_wd_var_k_c, "ML_Model/pdp_data/pdp_wd_var_k_c_rf.csv", row.names = FALSE)

### nitrogen 
pdp_model_n_var_k_c <- pdp::partial(rf_model_var_k_c, pred.var = "mean_diff_nitrogen")|>
  mutate(predictors = "mean_diff_nitrogen",
         model = "mean_diff_nitrogen w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_n_var_k_c, "ML_Model/pdp_data/pdp_n_var_k_c_rf.csv", row.names = FALSE)

### phosphor 
pdp_model_p_var_k_c <- pdp::partial(rf_model_var_k_c, pred.var = "mean_diff_phosphor")|>
  mutate(predictors = "mean_diff_phosphor",
         model = "mean_diff_phosphor w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_p_var_k_c, "ML_Model/pdp_data/pdp_p_var_k_c_rf.csv", row.names = FALSE)

### ecomorph_class 
pdp_model_e_var_k_c <- pdp::partial(rf_model_var_k_c, pred.var = "ecomorph_class")|>
  mutate(predictors = "ecomorph_class",
         model = "ecomorph_class w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_e_var_k_c, "ML_Model/pdp_data/pdp_e_var_k_c_rf.csv", row.names = FALSE)

### biogeo_int 
pdp_model_b_var_k_c <- pdp::partial(rf_model_var_k_c, pred.var = "biogeo_int")|>
  mutate(predictors = "biogeo_int",
         model = "biogeo_int w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_b_var_k_c, "ML_Model/pdp_data/pdp_b_var_k_c_rf.csv", row.names = FALSE)
```

# BRT
## Partial dependence plots
### Data extraction & export
```{r}
### PREDICTOR: VELOCITY ### -------------------------------------------------
# With k_index as response --------------------------------------------------
### velocity
train_v_k_c <- as.matrix(trainx_v_k_c[ ,-1])
colnames(train_v_k_c) <- "velocity"
pdp_model_v_k_c <- pdp::partial(xgb_v_k_c, pred.var = "velocity", train = train_v_k_c)|>
  mutate(predictors = "velocity_c",
         model = "velocity w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_k_c, "ML_Model/pdp_data/pdp_v_k_c_brt.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
train_v_s_c <- as.matrix(trainx_v_s_c[ ,-1])
colnames(train_v_s_c) <- "velocity"
pdp_model_v_s_c <- pdp::partial(xgb_v_s_c, pred.var = "velocity", train = train_v_s_c)|>
  mutate(predictors = "velocity_c",
         model = "velocity w/o coordinates",
         index = "shannon index")

# export data 
write.csv(pdp_model_v_s_c, "ML_Model/pdp_data/pdp_v_s_c_brt.csv", row.names = FALSE)

# With abundance as response --------------------------------------------------
### velocity 
train_v_a_c <- as.matrix(trainx_v_a_c[ ,-1])
colnames(train_v_a_c) <- "velocity"
pdp_model_v_a_c <- pdp::partial(xgb_v_a_c, pred.var = "velocity", train = train_v_a_c)|>
  mutate(predictors = "velocity_c",
         model = "velocity w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_a_c, "ML_Model/pdp_data/pdp_v_a_c_brt.csv", row.names = FALSE)

# With rel_abundance as response ----------------------------------------------
### velocity 
train_v_ra_c <- as.matrix(trainx_v_ra_c[ ,-1])
colnames(train_v_ra_c) <- "velocity"
pdp_model_v_ra_c <- pdp::partial(xgb_v_ra_c, pred.var = "velocity", train = train_v_ra_c)|>
  mutate(predictors = "velocity_c",
         model = "velocity w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_ra_c, "ML_Model/pdp_data/pdp_v_ra_c_brt.csv", row.names = FALSE)

### PREDICTORS: VELOCITY + WD ### --------------------------------------------
# With k_index as response ---------------------------------------------------
### velocity 
pdp_model_v_wd_k_c <- pdp::partial(xgb_wd_k_c, pred.var = "velocity", train = trainx_wd_k_c[ ,-1])|>
  mutate(predictors = "velocity_c",
         model = "v + wd w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_wd_k_c, "ML_Model/pdp_data/pdp_v_wd_k_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_k_c <- pdp::partial(xgb_wd_k_c, pred.var = "wd_m", train = trainx_wd_k_c[ ,-1])|>
  mutate(predictors = "wd_m_c",
         model = "v + wd w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_wd_k_c, "ML_Model/pdp_data/pdp_wd_k_c_brt.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
pdp_model_v_wd_s_c <- pdp::partial(xgb_wd_s_c, pred.var = "velocity", train = trainx_wd_s_c[ ,-1])|>
  mutate(predictors = "velocity_c",
         model = "v + wd w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_v_wd_s_c, "ML_Model/pdp_data/pdp_v_wd_s_c_brt.csv", row.names = FALSE)

### wd_m
pdp_model_wd_s_c <- pdp::partial(xgb_wd_s_c, pred.var = "wd_m", train = trainx_wd_s_c[ ,-1])|>
  mutate(predictors = "wd_m_c",
         model = "v + wd w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_wd_s_c, "ML_Model/pdp_data/pdp_wd_s_c_brt.csv", row.names = FALSE)

# With abundance as response --------------------------------------------------
### velocity 
pdp_model_v_wd_a_c <- pdp::partial(xgb_wd_a_c, pred.var = "velocity", train = trainx_wd_a_c[ ,-1])|>
  mutate(predictors = "velocity",
         model = "v + wd w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_wd_a_c, "ML_Model/pdp_data/pdp_v_wd_a_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_a_c <- pdp::partial(xgb_wd_a_c, pred.var = "wd_m", train = trainx_wd_a_c[ ,-1])|>
  mutate(predictors = "wd_m_c",
         model = "v + wd w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_wd_a_c, "ML_Model/pdp_data/pdp_wd_a_c_brt.csv", row.names = FALSE)

# With rel_abundance as response ---------------------------------------------
### velocity
pdp_model_v_wd_ra_c <- pdp::partial(xgb_wd_ra_c, pred.var = "velocity", train = trainx_wd_ra_c[ ,-1])|>
  mutate(predictors = "velocity_c",
         model = "v + wd w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_wd_ra_c, "ML_Model/pdp_data/pdp_v_wd_ra_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_ra_c <- pdp::partial(xgb_wd_ra_c, pred.var = "wd_m", train = trainx_wd_ra_c[ ,-1]) |>
  mutate(predictors = "wd_m_c",
         model = "v + wd w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_wd_ra_c, "ML_Model/pdp_data/pdp_wd_ra_c_brt.csv", row.names = FALSE)

### PREDICTORS: SAMPLING LOCATIONS ### ---------------------------------------
# With k_index as response ---------------------------------------------------
### velocity 
pdp_model_v_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "velocity", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_samp_k_c, "ML_Model/pdp_data/pdp_v_samp_k_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "wd_m", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_wd_samp_k_c, "ML_Model/pdp_data/pdp_wd_samp_k_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "z", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "z_c",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_z_samp_k_c, "ML_Model/pdp_data/pdp_z_samp_k_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "dist_w", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "dist_w_c",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_dist_samp_k_c, "ML_Model/pdp_data/pdp_dist_samp_k_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "cat_velocity", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cv_samp_k_c, "ML_Model/pdp_data/pdp_cv_samp_k_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "alg_cover", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ac_samp_k_c, "ML_Model/pdp_data/pdp_ac_samp_k_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "moos_cover", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_mc_samp_k_c, "ML_Model/pdp_data/pdp_mc_samp_k_c_brt.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "cpom_cover", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cc_samp_k_c, "ML_Model/pdp_data/pdp_cc_samp_k_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "clog_3_class_int", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_3_samp_k_c, "ML_Model/pdp_data/pdp_clog_3_samp_k_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "clog_6_class_int", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_6_samp_k_c, "ML_Model/pdp_data/pdp_clog_6_samp_k_c_brt.csv", row.names = FALSE)

### sub_type
pdp_model_sub_samp_k_c <- pdp::partial(xgb_samp_k_c, pred.var = "sub_type_int", train = trainx_samp_k_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_sub_samp_k_c, "ML_Model/pdp_data/pdp_sub_samp_k_c_brt.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
pdp_model_v_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "velocity", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_v_samp_s_c, "ML_Model/pdp_data/pdp_v_samp_s_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "wd_m", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_wd_samp_s_c, "ML_Model/pdp_data/pdp_wd_samp_s_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "z", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_z_samp_s_c, "ML_Model/pdp_data/pdp_z_samp_s_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "dist_w", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_dist_samp_s_c, "ML_Model/pdp_data/pdp_dist_samp_s_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "cat_velocity", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cv_samp_s_c, "ML_Model/pdp_data/pdp_cv_samp_s_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "alg_cover", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ac_samp_s_c, "ML_Model/pdp_data/pdp_ac_samp_s_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "moos_cover", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_mc_samp_s_c, "ML_Model/pdp_data/pdp_mc_samp_s_c_brt.csv", row.names = FALSE)

### cpom_cover
pdp_model_cc_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "cpom_cover", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cc_samp_s_c, "ML_Model/pdp_data/pdp_cc_samp_s_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "clog_3_class_int", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_3_samp_s_c, "ML_Model/pdp_data/pdp_clog_3_samp_s_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "clog_6_class_int", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_6_samp_s_c, "ML_Model/pdp_data/pdp_clog_6_samp_s_c_brt.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_samp_s_c <- pdp::partial(xgb_samp_s_c, pred.var = "sub_type_int", train = trainx_samp_s_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_sub_samp_s_c, "ML_Model/pdp_data/pdp_sub_samp_s_c_brt.csv", row.names = FALSE)

# With abundance as response --------------------------------------------------
### velocity 
pdp_model_v_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "velocity", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_samp_a_c, "ML_Model/pdp_data/pdp_v_samp_a_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "wd_m", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_wd_samp_a_c, "ML_Model/pdp_data/pdp_wd_samp_a_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "z", train = trainx_samp_a_c[,-1]) |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_z_samp_a_c, "ML_Model/pdp_data/pdp_z_samp_a_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "dist_w", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_dist_samp_a_c, "ML_Model/pdp_data/pdp_dist_samp_a_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "cat_velocity", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cv_samp_a_c, "ML_Model/pdp_data/pdp_cv_samp_a_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "alg_cover", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ac_samp_a_c, "ML_Model/pdp_data/pdp_ac_samp_a_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "moos_cover", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_mc_samp_a_c, "ML_Model/pdp_data/pdp_mc_samp_a_c_brt.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "cpom_cover", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cc_samp_a_c, "ML_Model/pdp_data/pdp_cc_samp_a_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "clog_3_class_int", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_3_samp_a_c, "ML_Model/pdp_data/pdp_clog_3_samp_a_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "clog_6_class_int", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_6_samp_a_c, "ML_Model/pdp_data/pdp_clog_6_samp_a_c_brt.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_samp_a_c <- pdp::partial(xgb_samp_a_c, pred.var = "sub_type_int", train = trainx_samp_a_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_sub_samp_a_c, "ML_Model/pdp_data/pdp_sub_samp_a_c_brt.csv", row.names = FALSE)

# With rel_abundance as response ----------------------------------------------
### velocity 
pdp_model_v_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "velocity", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_samp_ra_c, "ML_Model/pdp_data/pdp_v_samp_ra_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "wd_m", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_wd_samp_ra_c, "ML_Model/pdp_data/pdp_wd_samp_ra_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "z", train = trainx_samp_ra_c[,-1]) |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_z_samp_ra_c, "ML_Model/pdp_data/pdp_z_samp_ra_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "dist_w", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_dist_samp_ra_c, "ML_Model/pdp_data/pdp_dist_samp_ra_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "cat_velocity", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cv_samp_ra_c, "ML_Model/pdp_data/pdp_cv_samp_ra_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "alg_cover", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ac_samp_ra_c, "ML_Model/pdp_data/pdp_ac_samp_ra_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "moos_cover", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_mc_samp_ra_c, "ML_Model/pdp_data/pdp_mc_samp_ra_c_brt.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "cpom_cover", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cc_samp_ra_c, "ML_Model/pdp_data/pdp_cc_samp_ra_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "clog_3_class_int", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_3_samp_ra_c, "ML_Model/pdp_data/pdp_clog_3_samp_ra_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "clog_6_class_int", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_6_samp_ra_c, "ML_Model/pdp_data/pdp_clog_6_samp_ra_c_brt.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_samp_ra_c <- pdp::partial(xgb_samp_ra_c, pred.var = "sub_type_int", train = trainx_samp_ra_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_sub_samp_ra_c, "ML_Model/pdp_data/pdp_sub_samp_ra_c_brt.csv", row.names = FALSE)

### PREDICTORS: ALL PREDICTORS ### --------------------------------------------
# With k_index as response ----------------------------------------------------
### velocity 
pdp_model_v_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "velocity", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_v_sec_k_c, "ML_Model/pdp_data/pdp_v_sec_k_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "wd_m", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_wd_sec_k_c, "ML_Model/pdp_data/pdp_wd_sec_k_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "z", train = trainx_sec_k_c[,-1]) |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_z_sec_k_c, "ML_Model/pdp_data/pdp_z_sec_k_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "dist_w", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_dist_sec_k_c, "ML_Model/pdp_data/pdp_dist_sec_k_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "cat_velocity", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cv_sec_k_c, "ML_Model/pdp_data/pdp_cv_sec_k_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "alg_cover", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ac_sec_k_c, "ML_Model/pdp_data/pdp_ac_sec_k_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "moos_cover", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_mc_sec_k_c, "ML_Model/pdp_data/pdp_mc_sec_k_c_brt.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "cpom_cover", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cc_sec_k_c, "ML_Model/pdp_data/pdp_cc_sec_k_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "clog_3_class_int", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_3_sec_k_c, "ML_Model/pdp_data/pdp_clog_3_sec_k_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "clog_6_class_int", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_clog_6_sec_k_c, "ML_Model/pdp_data/pdp_clog_6_sec_k_c_brt.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "sub_type_int", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_sub_sec_k_c, "ML_Model/pdp_data/pdp_sub_sec_k_c_brt.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "pH_before", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "pH_before",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_phb_sec_k_c, "ML_Model/pdp_data/pdp_phb_sec_k_c_brt.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "pH_during", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "pH_during",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_phd_sec_k_c, "ML_Model/pdp_data/pdp_phd_sec_k_c_brt.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "pH_after", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "pH_after",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_pha_sec_k_c, "ML_Model/pdp_data/pdp_pha_sec_k_c_brt.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "conduct_before", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "conduct_before",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cb_sec_k_c, "ML_Model/pdp_data/pdp_cb_sec_k_c_brt.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "conduct_during", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "conduct_during",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_cd_sec_k_c, "ML_Model/pdp_data/pdp_cd_sec_k_c_brt.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "conduct_after", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "conduct_after",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ca_sec_k_c, "ML_Model/pdp_data/pdp_ca_sec_k_c_brt.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "ox_before", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "ox_before",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ob_sec_k_c, "ML_Model/pdp_data/pdp_ob_sec_k_c_brt.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "ox_during", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "ox_during",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_od_sec_k_c, "ML_Model/pdp_data/pdp_od_sec_k_c_brt.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "ox_after", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "ox_after",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_oa_sec_k_c, "ML_Model/pdp_data/pdp_oa_sec_k_c_brt.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "turb_before", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "turb_before",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_tb_sec_k_c, "ML_Model/pdp_data/pdp_tb_sec_k_c_brt.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "turb_during", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "turb_during",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_td_sec_k_c, "ML_Model/pdp_data/pdp_td_sec_k_c_brt.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "turb_after", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "turb_after",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ta_sec_k_c, "ML_Model/pdp_data/pdp_ta_sec_k_c_brt.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "temp_before", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "temp_before",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_teb_sec_k_c, "ML_Model/pdp_data/pdp_teb_sec_k_c_brt.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "temp_during", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "temp_during",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ted_sec_k_c, "ML_Model/pdp_data/pdp_ted_sec_k_c_brt.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "temp_after", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "temp_after",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_tea_sec_k_c, "ML_Model/pdp_data/pdp_tea_sec_k_c_brt.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "q_before", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "q_before",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_qb_sec_k_c, "ML_Model/pdp_data/pdp_qb_sec_k_c_brt.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "q_during", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "q_during",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_qd_sec_k_c, "ML_Model/pdp_data/pdp_qd_sec_k_c_brt.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "q_after", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "q_after",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_qa_sec_k_c, "ML_Model/pdp_data/pdp_qa_sec_k_c_brt.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "gaug_before", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "gaug_before",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_gb_sec_k_c, "ML_Model/pdp_data/pdp_gb_sec_k_c_brt.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "gaug_during", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "gaug_during",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_gd_sec_k_c, "ML_Model/pdp_data/pdp_gd_sec_k_c_brt.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_k_c <- pdp::partial(xgb_sec_k_c, pred.var = "gaug_after", train = trainx_sec_k_c[ ,-1]) |>
  mutate(predictors = "gaug_after",
         model = "sampling w/o coordinates",
         index = "k_index")

# export data 
write.csv(pdp_model_ga_sec_k_c, "ML_Model/pdp_data/pdp_ga_sec_k_c_brt.csv", row.names = FALSE)

# With shannon index as response ----------------------------------------------
### velocity 
pdp_model_v_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "velocity", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_v_sec_s_c, "ML_Model/pdp_data/pdp_v_sec_s_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "wd_m", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_wd_sec_s_c, "ML_Model/pdp_data/pdp_wd_sec_s_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "z", train = trainx_sec_s_c[,-1]) |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_z_sec_s_c, "ML_Model/pdp_data/pdp_z_sec_s_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "dist_w", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_dist_sec_s_c, "ML_Model/pdp_data/pdp_dist_sec_s_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "cat_velocity", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cv_sec_s_c, "ML_Model/pdp_data/pdp_cv_sec_s_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "alg_cover", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ac_sec_s_c, "ML_Model/pdp_data/pdp_ac_sec_s_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "moos_cover", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_mc_sec_s_c, "ML_Model/pdp_data/pdp_mc_sec_s_c_brt.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "cpom_cover", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cc_sec_s_c, "ML_Model/pdp_data/pdp_cc_sec_s_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "clog_3_class_int", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_3_sec_s_c, "ML_Model/pdp_data/pdp_clog_3_sec_s_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "clog_6_class_int", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_clog_6_sec_s_c, "ML_Model/pdp_data/pdp_clog_6_sec_s_c_brt.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "sub_type_int", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_sub_sec_s_c, "ML_Model/pdp_data/pdp_sub_sec_s_c_brt.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "pH_before", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "pH_before",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_phb_sec_s_c, "ML_Model/pdp_data/pdp_phb_sec_s_c_brt.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "pH_during", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "pH_during",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_phd_sec_s_c, "ML_Model/pdp_data/pdp_phd_sec_s_c_brt.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "pH_after", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "pH_after",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_pha_sec_s_c, "ML_Model/pdp_data/pdp_pha_sec_s_c_brt.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "conduct_before", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "conduct_before",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cb_sec_s_c, "ML_Model/pdp_data/pdp_cb_sec_s_c_brt.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "conduct_during", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "conduct_during",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_cd_sec_s_c, "ML_Model/pdp_data/pdp_cd_sec_s_c_brt.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "conduct_after", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "conduct_after",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ca_sec_s_c, "ML_Model/pdp_data/pdp_ca_sec_s_c_brt.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "ox_before", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "ox_before",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ob_sec_s_c, "ML_Model/pdp_data/pdp_ob_sec_s_c_brt.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "ox_during", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "ox_during",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_od_sec_s_c, "ML_Model/pdp_data/pdp_od_sec_s_c_brt.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "ox_after", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "ox_after",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_oa_sec_s_c, "ML_Model/pdp_data/pdp_oa_sec_s_c_brt.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "turb_before", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "turb_before",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_tb_sec_s_c, "ML_Model/pdp_data/pdp_tb_sec_s_c_brt.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "turb_during", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "turb_during",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_td_sec_s_c, "ML_Model/pdp_data/pdp_td_sec_s_c_brt.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "turb_after", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "turb_after",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ta_sec_s_c, "ML_Model/pdp_data/pdp_ta_sec_s_c_brt.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "temp_before", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "temp_before",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_teb_sec_s_c, "ML_Model/pdp_data/pdp_teb_sec_s_c_brt.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "temp_during", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "temp_during",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ted_sec_s_c, "ML_Model/pdp_data/pdp_ted_sec_s_c_brt.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "temp_after", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "temp_after",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_tea_sec_s_c, "ML_Model/pdp_data/pdp_tea_sec_s_c_brt.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "q_before", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "q_before",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_qb_sec_s_c, "ML_Model/pdp_data/pdp_qb_sec_s_c_brt.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "q_during", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "q_during",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_qd_sec_s_c, "ML_Model/pdp_data/pdp_qd_sec_s_c_brt.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "q_after", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "q_after",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_qa_sec_s_c, "ML_Model/pdp_data/pdp_qa_sec_s_c_brt.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "gaug_before", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "gaug_before",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_gb_sec_s_c, "ML_Model/pdp_data/pdp_gb_sec_s_c_brt.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "gaug_during", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "gaug_during",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_gd_sec_s_c, "ML_Model/pdp_data/pdp_gd_sec_s_c_brt.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_s_c <- pdp::partial(xgb_sec_s_c, pred.var = "gaug_after", train = trainx_sec_s_c[ ,-1]) |>
  mutate(predictors = "gaug_after",
         model = "sampling w/o coordinates",
         index = "shannon_index")

# export data 
write.csv(pdp_model_ga_sec_s_c, "ML_Model/pdp_data/pdp_ga_sec_s_c_brt.csv", row.names = FALSE)

# With abundance as response ----------------------------------------------
### velocity 
pdp_model_v_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "velocity", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_v_sec_a_c, "ML_Model/pdp_data/pdp_v_sec_a_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "wd_m", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_wd_sec_a_c, "ML_Model/pdp_data/pdp_wd_sec_a_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "z", train = trainx_sec_a_c[,-1]) |>
  mutate(predictors = "z",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_z_sec_a_c, "ML_Model/pdp_data/pdp_z_sec_a_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "dist_w", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "dist_w",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_dist_sec_a_c, "ML_Model/pdp_data/pdp_dist_sec_a_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "cat_velocity", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cv_sec_a_c, "ML_Model/pdp_data/pdp_cv_sec_a_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "alg_cover", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ac_sec_a_c, "ML_Model/pdp_data/pdp_ac_sec_a_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "moos_cover", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_mc_sec_a_c, "ML_Model/pdp_data/pdp_mc_sec_a_c_brt.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "cpom_cover", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cc_sec_a_c, "ML_Model/pdp_data/pdp_cc_sec_a_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "clog_3_class_int", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_3_sec_a_c, "ML_Model/pdp_data/pdp_clog_3_sec_a_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "clog_6_class_int", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_clog_6_sec_a_c, "ML_Model/pdp_data/pdp_clog_6_sec_a_c_brt.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "sub_type_int", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_sub_sec_a_c, "ML_Model/pdp_data/pdp_sub_sec_a_c_brt.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "pH_before", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "pH_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_phb_sec_a_c, "ML_Model/pdp_data/pdp_phb_sec_a_c_brt.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "pH_during", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "pH_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_phd_sec_a_c, "ML_Model/pdp_data/pdp_phd_sec_a_c_brt.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "pH_after", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "pH_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_pha_sec_a_c, "ML_Model/pdp_data/pdp_pha_sec_a_c_brt.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "conduct_before", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "conduct_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cb_sec_a_c, "ML_Model/pdp_data/pdp_cb_sec_a_c_brt.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "conduct_during", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "conduct_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_cd_sec_a_c, "ML_Model/pdp_data/pdp_cd_sec_a_c_brt.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "conduct_after", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "conduct_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ca_sec_a_c, "ML_Model/pdp_data/pdp_ca_sec_a_c_brt.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "ox_before", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "ox_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ob_sec_a_c, "ML_Model/pdp_data/pdp_ob_sec_a_c_brt.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "ox_during", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "ox_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_od_sec_a_c, "ML_Model/pdp_data/pdp_od_sec_a_c_brt.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "ox_after", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "ox_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_oa_sec_a_c, "ML_Model/pdp_data/pdp_oa_sec_a_c_brt.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "turb_before", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "turb_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_tb_sec_a_c, "ML_Model/pdp_data/pdp_tb_sec_a_c_brt.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "turb_during", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "turb_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_td_sec_a_c, "ML_Model/pdp_data/pdp_td_sec_a_c_brt.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "turb_after", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "turb_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ta_sec_a_c, "ML_Model/pdp_data/pdp_ta_sec_a_c_brt.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "temp_before", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "temp_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_teb_sec_a_c, "ML_Model/pdp_data/pdp_teb_sec_a_c_brt.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "temp_during", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "temp_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ted_sec_a_c, "ML_Model/pdp_data/pdp_ted_sec_a_c_brt.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "temp_after", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "temp_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_tea_sec_a_c, "ML_Model/pdp_data/pdp_tea_sec_a_c_brt.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "q_before", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "q_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_qb_sec_a_c, "ML_Model/pdp_data/pdp_qb_sec_a_c_brt.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "q_during", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "q_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_qd_sec_a_c, "ML_Model/pdp_data/pdp_qd_sec_a_c_brt.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "q_after", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "q_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_qa_sec_a_c, "ML_Model/pdp_data/pdp_qa_sec_a_c_brt.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "gaug_before", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "gaug_before",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_gb_sec_a_c, "ML_Model/pdp_data/pdp_gb_sec_a_c_brt.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "gaug_during", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "gaug_during",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_gd_sec_a_c, "ML_Model/pdp_data/pdp_gd_sec_a_c_brt.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_a_c <- pdp::partial(xgb_sec_a_c, pred.var = "gaug_after", train = trainx_sec_a_c[ ,-1]) |>
  mutate(predictors = "gaug_after",
         model = "all predictors w/o coordinates",
         index = "abundance")

# export data 
write.csv(pdp_model_ga_sec_a_c, "ML_Model/pdp_data/pdp_ga_sec_a_c_brt.csv", row.names = FALSE)

# With rel_abundance as response ----------------------------------------------
### velocity 
pdp_model_v_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "velocity", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "velocity",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_v_sec_ra_c, "ML_Model/pdp_data/pdp_v_sec_ra_c_brt.csv", row.names = FALSE)

### wd_m 
pdp_model_wd_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "wd_m", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "wd_m",
         model = "all predictors w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_wd_sec_ra_c, "ML_Model/pdp_data/pdp_wd_sec_ra_c_brt.csv", row.names = FALSE)

### z 
pdp_model_z_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "z", train = trainx_sec_ra_c[,-1]) |>
  mutate(predictors = "z",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_z_sec_ra_c, "ML_Model/pdp_data/pdp_z_sec_ra_c_brt.csv", row.names = FALSE)

### dist_w 
pdp_model_dist_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "dist_w", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "dist_w",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_dist_sec_ra_c, "ML_Model/pdp_data/pdp_dist_sec_ra_c_brt.csv", row.names = FALSE)

### cat_v 
pdp_model_cv_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "cat_velocity", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "cat_velocity",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cv_sec_ra_c, "ML_Model/pdp_data/pdp_cv_sec_ra_c_brt.csv", row.names = FALSE)

### alg_cover 
pdp_model_ac_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "alg_cover", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "alg_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ac_sec_ra_c, "ML_Model/pdp_data/pdp_ac_sec_ra_c_brt.csv", row.names = FALSE)

### moos_cover 
pdp_model_mc_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "moos_cover", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "moos_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_mc_sec_ra_c, "ML_Model/pdp_data/pdp_mc_sec_ra_c_brt.csv", row.names = FALSE)

### cpom_cover 
pdp_model_cc_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "cpom_cover", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "cpom_cover",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cc_sec_ra_c, "ML_Model/pdp_data/pdp_cc_sec_ra_c_brt.csv", row.names = FALSE)

### clog_3 
pdp_model_clog_3_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "clog_3_class_int", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "clog_3_class",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_3_sec_ra_c, "ML_Model/pdp_data/pdp_clog_3_sec_ra_c_brt.csv", row.names = FALSE)

### clog_6
pdp_model_clog_6_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "clog_6_class_int", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "clog_6_class",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_clog_6_sec_ra_c, "ML_Model/pdp_data/pdp_clog_6_sec_ra_c_brt.csv", row.names = FALSE)

### sub_type 
pdp_model_sub_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "sub_type_int", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "sub_type",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_sub_sec_ra_c, "ML_Model/pdp_data/pdp_sub_sec_ra_c_brt.csv", row.names = FALSE)

### pH_before
pdp_model_phb_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "pH_before", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "pH_before",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_phb_sec_ra_c, "ML_Model/pdp_data/pdp_phb_sec_ra_c_brt.csv", row.names = FALSE)

### pH_during
pdp_model_phd_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "pH_during", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "pH_during",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_phd_sec_ra_c, "ML_Model/pdp_data/pdp_phd_sec_ra_c_brt.csv", row.names = FALSE)

### pH_after
pdp_model_pha_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "pH_after", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "pH_after",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_pha_sec_ra_c, "ML_Model/pdp_data/pdp_pha_sec_ra_c_brt.csv", row.names = FALSE)

### conduct_before
pdp_model_cb_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "conduct_before", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "conduct_before",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cb_sec_ra_c, "ML_Model/pdp_data/pdp_cb_sec_ra_c_brt.csv", row.names = FALSE)

### conduct_during
pdp_model_cd_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "conduct_during", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "conduct_during",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_cd_sec_ra_c, "ML_Model/pdp_data/pdp_cd_sec_ra_c_brt.csv", row.names = FALSE)

### conduct_after
pdp_model_ca_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "conduct_after", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "conduct_after",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ca_sec_ra_c, "ML_Model/pdp_data/pdp_ca_sec_ra_c_brt.csv", row.names = FALSE)

### ox_before
pdp_model_ob_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "ox_before", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "ox_before",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ob_sec_ra_c, "ML_Model/pdp_data/pdp_ob_sec_ra_c_brt.csv", row.names = FALSE)

### ox_during
pdp_model_od_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "ox_during", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "ox_during",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_od_sec_ra_c, "ML_Model/pdp_data/pdp_od_sec_ra_c_brt.csv", row.names = FALSE)

### ox_after
pdp_model_oa_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "ox_after", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "ox_after",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_oa_sec_ra_c, "ML_Model/pdp_data/pdp_oa_sec_ra_c_brt.csv", row.names = FALSE)

### turb_before
pdp_model_tb_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "turb_before", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "turb_before",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_tb_sec_ra_c, "ML_Model/pdp_data/pdp_tb_sec_ra_c_brt.csv", row.names = FALSE)

### turb_during
pdp_model_td_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "turb_during", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "turb_during",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_td_sec_ra_c, "ML_Model/pdp_data/pdp_td_sec_ra_c_brt.csv", row.names = FALSE)

### turb_after
pdp_model_ta_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "turb_after", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "turb_after",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ta_sec_ra_c, "ML_Model/pdp_data/pdp_ta_sec_ra_c_brt.csv", row.names = FALSE)

### temp_before
pdp_model_teb_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "temp_before", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "temp_before",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_teb_sec_ra_c, "ML_Model/pdp_data/pdp_teb_sec_ra_c_brt.csv", row.names = FALSE)

### temp_during
pdp_model_ted_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "temp_during", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "temp_during",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ted_sec_ra_c, "ML_Model/pdp_data/pdp_ted_sec_ra_c_brt.csv", row.names = FALSE)

### temp_after
pdp_model_tea_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "temp_after", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "temp_after",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_tea_sec_ra_c, "ML_Model/pdp_data/pdp_tea_sec_ra_c_brt.csv", row.names = FALSE)

### q_before
pdp_model_qb_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "q_before", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "q_before",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_qb_sec_ra_c, "ML_Model/pdp_data/pdp_qb_sec_ra_c_brt.csv", row.names = FALSE)

### q_during
pdp_model_qd_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "q_during", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "q_during",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_qd_sec_ra_c, "ML_Model/pdp_data/pdp_qd_sec_ra_c_brt.csv", row.names = FALSE)

### q_after
pdp_model_qa_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "q_after", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "q_after",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_qa_sec_ra_c, "ML_Model/pdp_data/pdp_qa_sec_ra_c_brt.csv", row.names = FALSE)

### gaug_before
pdp_model_gb_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "gaug_before", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "gaug_before",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_gb_sec_ra_c, "ML_Model/pdp_data/pdp_gb_sec_ra_c_brt.csv", row.names = FALSE)

### gaug_during
pdp_model_gd_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "gaug_during", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "gaug_during",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_gd_sec_ra_c, "ML_Model/pdp_data/pdp_gd_sec_ra_c_brt.csv", row.names = FALSE)

### gaug_after
pdp_model_ga_sec_ra_c <- pdp::partial(xgb_sec_ra_c, pred.var = "gaug_after", train = trainx_sec_ra_c[ ,-1]) |>
  mutate(predictors = "gaug_after",
         model = "sampling w/o coordinates",
         index = "rel_abundance")

# export data 
write.csv(pdp_model_ga_sec_ra_c, "ML_Model/pdp_data/pdp_ga_sec_ra_c_brt.csv", row.names = FALSE)
```