---
title: "basement_function"
format: html
---

# Load packages
```{r}
rm(list = ls())

# load all Packages ---
library(hdf5r)
library(sp)
library(sf)
library(ggplot2)
library(dplyr)
library(readr)
library(Metrics)
library(raster)
library(rgeos)
library(hydroGOF)
library(jsonlite)

source("mth_functions.R")
```


# Glenner
## GL1
```{r}
GL1_3.28 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_3.28.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_3.28",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 3.28, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_6.00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_6.00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_6.00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 6.00, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_9.00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_9.00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_9.00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 9.00, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_12.68 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_12.68.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_12.68",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 12.68, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_16.00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_16.00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_16.00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 16.00, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_19.00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_19.00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_19.00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 19.00, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_22.00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_22.00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_22.00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 22.00, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_25.00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_25.00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_25.00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 25.00, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_28.00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_28.00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_28.00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 28.00, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)

GL1_31.76 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_31.76.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_31.76",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 31.76, 
                       strickler = 38, 
                       time_end = 3600,
                       slope = 0.01)
```



## GL2
```{r}
GL2_3.21 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_3.21.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_3.21",
             results_json = "hdm_models/GL2/results.json",
             discharge = 3.21, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_6.00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_6.00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_6.00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 6.00, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_9.00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_9.00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_9.00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 9.00, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_12.52 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_12.52.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_12.52",
             results_json = "hdm_models/GL2/results.json",
             discharge = 12.52, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_16.00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_16.00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_16.00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 16.00, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_19.00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_19.00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_19.00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 19.00, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_22.00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_22.00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_22.00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 22.00, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_25.00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_25.00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_25.00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 25.00, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_28.00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_28.00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_28.00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 28.00, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)

GL2_31.53 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_31.53.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_31.53",
             results_json = "hdm_models/GL2/results.json",
             discharge = 31.53, 
             strickler = 38, 
             time_end = 3600,
             slope = 0.01)
```

# Test Landquart
## L2
```{r}
L2_2.40 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_2.40.h5",
                     results_xdmf = "hdm_models/L2/results_L2_2.40",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 2.40, 
                     strickler = 11.5, 
                     time_end = 3600,
                     slope = 0.01)

L2_3.90 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_3.90.h5",
                     results_xdmf = "hdm_models/L2/results_L2_3.90",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 3.90, 
                     strickler = 11.5, 
                     time_end = 3600,
                     slope = 0.01)

L2_7.00 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_7.00.h5",
                     results_xdmf = "hdm_models/L2/results_L2_7.00",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 7.00, 
                     strickler = 11.5, 
                     time_end = 3600,
                     slope = 0.01)

L2_9.24 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_9.24.h5",
                     results_xdmf = "hdm_models/L2/results_L2_9.24",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 9.24, 
                     strickler = 11.5, 
                     time_end = 3600,
                     slope = 0.01)

L2_13.30 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_13.30.h5",
                     results_xdmf = "hdm_models/L2/results_L2_13.30",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 13.30, 
                     strickler = 11.5, 
                     time_end = 3600,
                     slope = 0.01)

L2_16.50 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_16.50.h5",
                     results_xdmf = "hdm_models/L2/results_L2_16.50",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 16.50, 
                     strickler = 11.5, 
                     time_end = 3600,
                     slope = 0.01)

L2_18.90 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_18.90.h5",
                     results_xdmf = "hdm_models/L2/results_L2_18.90",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 18.90, 
                     strickler = 11.5, 
                     time_end = 3600,
                     slope = 0.01)
```

# Moesa
## M1 
```{r}
M1_0.47 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_0.47.h5",
                       results_xdmf = "hdm_models/M1/results_M1_0.47",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 0.47, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_0.60 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_0.60.h5",
                       results_xdmf = "hdm_models/M1/results_M1_0.60",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 0.60, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_4.00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_4.00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_4.00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 4.00, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_6.00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_6.00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_6.00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 6.00, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)


M1_8.00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_8.00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_8.00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 8.00, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_10.00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_10.00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_10.00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 10.00, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_12.00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_12.00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_12.00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 12.00, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_14.00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_14.00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_14.00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 14.00, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_16.00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_16.00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_16.00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 16.00, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_18.84 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_18.84.h5",
                       results_xdmf = "hdm_models/M1/results_M1_18.84",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 18,84, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)

M1_22.84 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_22.84.h5",
                       results_xdmf = "hdm_models/M1/results_M1_22.84",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 22.84, 
                       strickler = 35.0, 
                       time_end = 3600,
                       slope = 0.01)
```

# Sitter
## S1
```{r}
S1_2.00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_2.00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_2.00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 2.00, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_3.70 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_3.70.h5",
                    results_xdmf = "hdm_models/S1/results_S1_3.70", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 3.70, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_6.50 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_6.50.h5",
                    results_xdmf = "hdm_models/S1/results_S1_6.50", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 6.50, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_8.50 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_8.50.h5",
                    results_xdmf = "hdm_models/S1/results_S1_8.50", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 8.50, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_10.68 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_10.68.h5",
                    results_xdmf = "hdm_models/S1/results_S1_10.68", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 10.68, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_13.00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_13.00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_13.00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 13.00, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_15.00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_15.00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_15.00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 15.00, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_18.00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_18.00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_18.00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 18.00, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)

S1_20.00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_20.00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_20.00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 20.00, 
                    strickler = 33.0, 
                    time_end = 3600,
                    slope = 0.001)
```

## S2
```{r}
S2_2.00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_2.00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_2.00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 2.00, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)

S2_3.20 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_3.20.h5",
                    results_xdmf = "hdm_models/S2/results_S2_3.20",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 3.20, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)

S2_6.50 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_6.50.h5",
                    results_xdmf = "hdm_models/S2/results_S2_6.50",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 6.50, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)

S2_8.50 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_8.50.h5",
                    results_xdmf = "hdm_models/S2/results_S2_8.50",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 8.50, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)

S2_10.93 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_10.93.h5",
                    results_xdmf = "hdm_models/S2/results_S2_10.93",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 10.93, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)

S2_13.00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_13.00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_13.00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 13.00, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)

S2_15.00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_15.00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_15.00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 15.00, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)

S2_18.00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_18.00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_18.00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 18.00, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)
       
S2_20.00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_20.00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_20.00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 10.00, 
                    strickler = 36.0, 
                    time_end = 3600,
                    slope = 0.003376)
```

# Thur
## TH4
```{r}
TH4_11.45 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_11.45.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_11.45",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 11.45, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_15.00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_15.00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_15.00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 15.00, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_18.00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_18.00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_18.00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 18.00, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_19.96 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_19.96.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_19.96",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 19.96, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_22.50 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_22.50.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_22.50",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 22.50, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_25.00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_25.00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_25.00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 25.00, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_27.00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_27.00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_27.00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 27.00, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_30.00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_30.00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_30.00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 30.00, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)

TH4_32.93 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_32.93.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_32.93",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 32.93, 
                      strickler = 42.0,
                      time_end = 3600,
                      slope = 0.001)
```

# Vorderrhein
## VR3
```{r}
VR3_2.90 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_2.90.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_2.90",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 2.90, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_6.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_6.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_6.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 6.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_9.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_9.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_9.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 9.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_12.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_12.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_12.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 12.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_15.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_15.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_15.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 15.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_18.80 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_18.80.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_18.80",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 18.80, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_22.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_22.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_22.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 22.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_25.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_25.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_25.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 25.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_28.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_28.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_28.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 28.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_31.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_31.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_31.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 31.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_34.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_34.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_34.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 34.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_37.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_37.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_37.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 37.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_40.10 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_40.10.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_40.10",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 40.10, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_43.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_43.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_43.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 43.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_46.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_46.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_46.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 46.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_48.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_48.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_48.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 48.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_50.00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_50.00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_50.00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 50.00, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)

VR3_52.90 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_52.90.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_52.90",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 52.90, 
                     strickler = 35.0, 
                     time_end = 3600,
                     slope = 0.001)
```