---
title: "Habitat_Model_VZH"
format: html
---

# Load packages 
```{r}
#clear R environment
rm(list = ls())

# check for a package, install and load 
pkgCheck <- function(x){ 
  if (!require(x,character.only = TRUE)){
    install.packages(x,dependencies=TRUE)
    if(!require(x,character.only = TRUE)) {
      stop()
    }
  }
}

pkgCheck("raster")
pkgCheck("spsurvey")
pkgCheck("terra")
pkgCheck("raster")
pkgCheck("ggplot2")
pkgCheck("tibble")
pkgCheck("readr")
pkgCheck("dplyr")
pkgCheck("tidyr")
pkgCheck("scales")

# load self-written functions 
source("mth_functions.R")
```

# Habitat Model FOEN
## Landqaurt: L2
### Velocity
```{r}
# L2 with Q: 2.4 m3/s
L2_2 <- foen_hm(raster_path = "raster_files/L2_v_2.tif", 
                base_flow = "raster_files/L2_v_2.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_2.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_2.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_2.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_2.tif", 
                river = "L2", discharge = 2.4)

# L2 with Q: 3.9 m3/s
L2_3 <- foen_hm(raster_path = "raster_files/L2_v_3.tif", 
                base_flow = "raster_files/L2_v_3.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_3.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_3.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_3.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_3.tif", 
                river = "L2", discharge = 3.9)

# L2 with Q: 4.6 m3/s
L2_4 <- foen_hm(raster_path = "raster_files/L2_v_4.tif", 
                base_flow = "raster_files/L2_v_4.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_4.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_4.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_4.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_4.tif", 
                river = "L2", discharge = 4.6)

# L2 with Q: 7 m3/s
L2_7 <- foen_hm(raster_path = "raster_files/L2_v_7.tif", 
                base_flow = "raster_files/L2_v_7.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_7.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_7.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_7.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_7.tif", 
                river = "L2", discharge = 7)

# L2 with Q: 9.24 m3/s
L2_9 <- foen_hm(raster_path = "raster_files/L2_v_9.tif", 
                base_flow = "raster_files/L2_v_9.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_9.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_9.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_9.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_9.tif", 
                river = "L2", discharge = 9.24)

# L2 with Q: 11.4 m3/s
L2_11 <- foen_hm(raster_path = "raster_files/L2_v_11.tif", 
                base_flow = "raster_files/L2_v_11.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_11.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_11.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_11.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_11.tif", 
                river = "L2", discharge = 11.4)

# L2 with Q: 13.3 m3/s
L2_13 <- foen_hm(raster_path = "raster_files/L2_v_13.tif", 
                base_flow = "raster_files/L2_v_13.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_13.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_13.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_13.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_13.tif", 
                river = "L2", discharge = 13.3)

# L2 with Q: 15 m3/s
L2_15 <- foen_hm(raster_path = "raster_files/L2_v_15.tif", 
                base_flow = "raster_files/L2_v_15.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_15.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_15.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_15.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_15.tif", 
                river = "L2", discharge = 15)

# L2 with Q: 18.9 m3/s
L2_18 <- foen_hm(raster_path = "raster_files/L2_v_18.tif", 
                base_flow = "raster_files/L2_v_18.tif",
                output_path_pers_reclass =
                  "results_foen/L2_foen_class_pers_18.tif", 
                output_path_reclass =
                  "results_foen/L2_foen_class_18.tif", 
                HSC_path = "HSC_MI/HSC_MI.csv", 
                output_path_hm = "results_foen/foen_18.tif",
                output_path_hm_persistent =
                  "results_foen/foen_pers_18.tif", 
                river = "L2", discharge = 18.9)
```

### Water depth
```{r}

```


## Moesa: MR
```{r}

```


# Bind Metric Results 
```{r}
# metrics
together <- rbind(Test$metrics, Test2$metrics)

# safe df into .csv file -----------------------------------
write.csv(results_VZH, file = "results_statistics/Results_VZH_Habitat_Model.csv", row.names = FALSE)

# freq_tables
together1 <- rbind(Test$freq, Test2$freq)

# write data frame into .csv file
write.csv(join, file = "results_statistics/VZH.csv", row.names = FALSE)
```




