---
title: "Habitat_Model_VZH"
format: html
---

# Load packages 
```{r}
#clear R environment
rm(list = ls())

# check for a package, install and load 
pkgCheck <- function(x){ 
  if (!require(x,character.only = TRUE)){
    install.packages(x,dependencies=TRUE)
    if(!require(x,character.only = TRUE)) {
      stop()
    }
  }
}

pkgCheck("raster")
pkgCheck("spsurvey")
pkgCheck("terra")
pkgCheck("raster")
pkgCheck("ggplot2")
pkgCheck("tibble")
pkgCheck("readr")
pkgCheck("dplyr")
pkgCheck("tidyr")
pkgCheck("scales")

# load self-written functions 
source("mth_functions.R")
```

# Glenner
## GL1
```{r}
GL1_3_28 <- foen_hm(raster_path = "raster_files/GL1_v_3_28.tif", 
                    base_flow = "raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_3_28.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_3_28.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_3_28.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_3_28.tif", 
                    river = "GL1", 
                    discharge = 3.28)

GL1_6_00 <- foen_hm(raster_path = "raster_files/GL1_v_6_00.tif", 
                    base_flow = "raster_files/GL1_v_6_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_6_00.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_6_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_6_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_6_00.tif", 
                    river = "GL1", 
                    discharge = 6.00)

GL1_9_00 <- foen_hm(raster_path = "raster_files/GL1_v_9_00.tif", 
                    base_flow = "raster_files/GL1_v_9_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_9_00.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_9_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_9_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_9_00.tif", 
                    river = "GL1", 
                    discharge = 9.00)

GL1_12_68 <- foen_hm(raster_path = "raster_files/GL1_v_12_68.tif", 
                    base_flow = "raster_files/GL1_v_12_68.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_12_68.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_12_68.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_12_68.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_12_68.tif", 
                    river = "GL1", 
                    discharge = 12.68)

GL1_16_00 <- foen_hm(raster_path = "raster_files/GL1_v_16_00.tif", 
                    base_flow = "raster_files/GL1_v_16_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_16_00.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_16_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_16_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_16_00.tif", 
                    river = "GL1", 
                    discharge = 16.00)

GL1_19_00 <- foen_hm(raster_path = "raster_files/GL1_v_19_00.tif", 
                    base_flow = "raster_files/GL1_v_19_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_19_00.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_19_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_19_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_19_00.tif", 
                    river = "GL1", 
                    discharge = 19.00)

GL1_22_00 <- foen_hm(raster_path = "raster_files/GL1_v_22_00.tif", 
                    base_flow = "raster_files/GL1_v_22_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_22_00.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_22_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_22_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_22_00.tif", 
                    river = "GL1", 
                    discharge = 22.00)

GL1_25_00 <- foen_hm(raster_path = "raster_files/GL1_v_25_00.tif", 
                    base_flow = "raster_files/GL1_v_25_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_25_00.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_25_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_25_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_25_00.tif", 
                    river = "GL1", 
                    discharge = 25.00)

GL1_28_00 <- foen_hm(raster_path = "raster_files/GL1_v_28_00.tif", 
                    base_flow = "raster_files/GL1_v_28_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_28_00.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_28_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_28_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_28_00.tif", 
                    river = "GL1", 
                    discharge = 28.00)

GL1_31_76 <- foen_hm(raster_path = "raster_files/GL1_v_31_76.tif", 
                    base_flow = "raster_files/GL1_v_31_76.tif",
                    output_path_pers_reclass =
                      "results_foen/GL1_foen_class_pers_31_76.tif", 
                    output_path_reclass =
                      "results_foen/GL1_foen_class_31_76.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL1_foen_31_76.tif",
                    output_path_hm_persistent =
                      "results_foen/GL1_foen_pers_31_76.tif", 
                    river = "GL1", 
                    discharge = 31.76)
```

## GL2
```{r}
GL2_3_21 <- foen_hm(raster_path = "raster_files/GL2_v_3_21.tif", 
                    base_flow = "raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_3_21.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_3_21.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_3_21.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_3_21.tif", 
                    river = "GL2", 
                    discharge = 3.21)

GL2_6_00 <- foen_hm(raster_path = "raster_files/GL2_v_6_00.tif", 
                    base_flow = "raster_files/GL2_v_6_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_6_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_6_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_6_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_6_00.tif", 
                    river = "GL2", 
                    discharge = 6.00)

GL2_9_00 <- foen_hm(raster_path = "raster_files/GL2_v_9_00.tif", 
                    base_flow = "raster_files/GL2_v_9_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_9_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_9_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_9_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_9_00.tif", 
                    river = "GL2", 
                    discharge = 9.00)

GL2_11_00 <- foen_hm(raster_path = "raster_files/GL2_v_11_00.tif", 
                    base_flow = "raster_files/GL2_v_11_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_11_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_11_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_11_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_11_00.tif", 
                    river = "GL2", 
                    discharge = 11.00)

GL2_12_52 <- foen_hm(raster_path = "raster_files/GL2_v_12_52.tif", 
                    base_flow = "raster_files/GL2_v_12_52.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_12_52.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_12_52.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_12_52.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_12_52.tif", 
                    river = "GL2", 
                    discharge = 12.52)

GL2_16_00 <- foen_hm(raster_path = "raster_files/GL2_v_16_00.tif", 
                    base_flow = "raster_files/GL2_v_16_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_16_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_16_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_16_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_16_00.tif", 
                    river = "GL2", 
                    discharge = 16.00)

GL2_19_00 <- foen_hm(raster_path = "raster_files/GL2_v_19_00.tif", 
                    base_flow = "raster_files/GL2_v_19_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_19_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_19_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_19_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_19_00.tif", 
                    river = "GL2", 
                    discharge = 19.00)

GL2_22_00 <- foen_hm(raster_path = "raster_files/GL2_v_22_00.tif", 
                    base_flow = "raster_files/GL2_v_22_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_22_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_22_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_22_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_22_00.tif", 
                    river = "GL2", 
                    discharge = 22.00)

GL2_25_00 <- foen_hm(raster_path = "raster_files/GL2_v_25_00.tif", 
                    base_flow = "raster_files/GL2_v_25_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_25_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_25_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_25_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_25_00.tif", 
                    river = "GL2", 
                    discharge = 25.00)


GL2_28_00 <- foen_hm(raster_path = "raster_files/GL2_v_28_00.tif", 
                    base_flow = "raster_files/GL2_v_28_00.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_28_00.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_28_00.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_28_00.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_28_00.tif", 
                    river = "GL2", 
                    discharge = 28.00)


GL2_31_53 <- foen_hm(raster_path = "raster_files/GL2_v_31_53.tif", 
                    base_flow = "raster_files/GL2_v_31_53.tif",
                    output_path_pers_reclass =
                      "results_foen/GL2_foen_class_pers_31_53.tif", 
                    output_path_reclass =
                      "results_foen/GL2_foen_class_31_53.tif", 
                    HSC_path = "HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "results_foen/GL2_foen_31_53.tif",
                    output_path_hm_persistent =
                      "results_foen/GL2_foen_pers_31_53.tif", 
                    river = "GL2", 
                    discharge = 31.53)
```

# Landquart
## L2
```{r}
L2_2_40 <- foen_hm(raster_path = "raster_files/L2_v_2_40.tif", 
                   base_flow = "raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_2_40.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_2_40.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_2_40.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_2_40.tif", 
                   river = "L2", 
                   discharge = 2.40)

L2_3_90 <- foen_hm(raster_path = "raster_files/L2_v_3_90.tif", 
                   base_flow = "raster_files/L2_v_3_90.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_3_90.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_3_90.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_3_90.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_3_90.tif", 
                   river = "L2", 
                   discharge = 3.90)

L2_7_00 <- foen_hm(raster_path = "raster_files/L2_v_7_00.tif", 
                   base_flow = "raster_files/L2_v_7_00.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_7_00.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_7_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_7_00.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_7_00.tif", 
                   river = "L2", 
                   discharge = 7.00)

L2_9_24 <- foen_hm(raster_path = "raster_files/L2_v_9_24.tif", 
                   base_flow = "raster_files/L2_v_9_24.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_9_24.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_9_24.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_9_24.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_9_24.tif", 
                   river = "L2", 
                   discharge = 9.24)

L2_11_40 <- foen_hm(raster_path = "raster_files/L2_v_11_40.tif", 
                   base_flow = "raster_files/L2_v_11_40.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_11_40.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_11_40.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_11_40.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_11_40.tif", 
                   river = "L2", 
                   discharge = 11.40)

L2_13_30 <- foen_hm(raster_path = "raster_files/L2_v_13_30.tif", 
                   base_flow = "raster_files/L2_v_13_30.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_13_30.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_13_30.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_13_30.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_13_30.tif", 
                   river = "L2", 
                   discharge = 13.30)

L2_16_50 <- foen_hm(raster_path = "raster_files/L2_v_16_50.tif", 
                   base_flow = "raster_files/L2_v_16_50.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_16_50.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_16_50.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_16_50.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_16_50.tif", 
                   river = "L2", 
                   discharge = 16.50)

L2_18_90 <- foen_hm(raster_path = "raster_files/L2_v_18_90.tif", 
                   base_flow = "raster_files/L2_v_18_90.tif",
                   output_path_pers_reclass =
                     "results_foen/L2_foen_class_pers_18_90.tif", 
                   output_path_reclass =
                     "results_foen/L2_foen_class_18_90.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/L2_foen_18_90.tif",
                   output_path_hm_persistent =
                     "results_foen/L2_foen_pers_18_90.tif", 
                   river = "L2", 
                   discharge = 18.90)
```


# Moesa
## M1
```{r}
M1_0_47 <- foen_hm(raster_path = "raster_files/M1_v_0_47.tif", 
                   base_flow = "raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_0_47.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_0_47.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_0_47.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_0_47.tif", 
                   river = "M1", 
                   discharge = 0.47)

M1_0_60 <- foen_hm(raster_path = "raster_files/M1_v_0_60.tif", 
                   base_flow = "raster_files/M1_v_0_60.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_0_60.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_0_60.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_0_60.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_0_60.tif", 
                   river = "M1", 
                   discharge = 0.60)

M1_4_00 <- foen_hm(raster_path = "raster_files/M1_v_4_00.tif", 
                   base_flow = "raster_files/M1_v_4_00.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_4_00.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_4_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_4_00.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_4_00.tif", 
                   river = "M1", 
                   discharge = 4.00)

M1_6_00 <- foen_hm(raster_path = "raster_files/M1_v_6_00.tif", 
                   base_flow = "raster_files/M1_v_6_00.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_6_00.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_6_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_6_00.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_6_00.tif", 
                   river = "M1", 
                   discharge = 6.00)

M1_8_00 <- foen_hm(raster_path = "raster_files/M1_v_8_00.tif", 
                   base_flow = "raster_files/M1_v_8_00.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_8_00.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_8_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_8_00.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_8_00.tif", 
                   river = "M1", 
                   discharge = 8.00)

M1_10_00 <- foen_hm(raster_path = "raster_files/M1_v_10_00.tif", 
                   base_flow = "raster_files/M1_v_10_00.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_10_00.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_10_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_10_00.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_10_00.tif", 
                   river = "M1", 
                   discharge = 10.00)

M1_12_00 <- foen_hm(raster_path = "raster_files/M1_v_12_00.tif", 
                   base_flow = "raster_files/M1_v_12_00.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_12_00.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_12_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_12_00.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_12_00.tif", 
                   river = "M1", 
                   discharge = 12.00)

M1_14_00 <- foen_hm(raster_path = "raster_files/M1_v_14_00.tif", 
                   base_flow = "raster_files/M1_v_14_00.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_14_00.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_14_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_14_00.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_14_00.tif", 
                   river = "M1", 
                   discharge = 14.00)

M1_16_00 <- foen_hm(raster_path = "raster_files/M1_v_16_00.tif", 
                   base_flow = "raster_files/M1_v_16_00.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_16_00.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_16_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_16_00.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_16_00.tif", 
                   river = "M1", 
                   discharge = 16.00)

M1_18_84 <- foen_hm(raster_path = "raster_files/M1_v_18_84.tif", 
                   base_flow = "raster_files/M1_v_18_84.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_18_84.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_18_84.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_18_84.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_18_84.tif", 
                   river = "M1", 
                   discharge = 18.84)

M1_22_84 <- foen_hm(raster_path = "raster_files/M1_v_22_84.tif", 
                   base_flow = "raster_files/M1_v_22_84.tif",
                   output_path_pers_reclass =
                     "results_foen/M1_foen_class_pers_22_84.tif", 
                   output_path_reclass =
                     "results_foen/M1_foen_class_22_84.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/M1_foen_22_84.tif",
                   output_path_hm_persistent =
                     "results_foen/M1_foen_pers_22_84.tif", 
                   river = "M1", 
                   discharge = 22.84)
```

# Sitter
## S1
```{r}
S1_2_00 <- foen_hm(raster_path = "raster_files/S1_v_2_00.tif", 
                   base_flow = "raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_2_00.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_2_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_2_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_2_00.tif", 
                   river = "S1", 
                   discharge = 2.00)

S1_3_70 <- foen_hm(raster_path = "raster_files/S1_v_3_70.tif", 
                   base_flow = "raster_files/S1_v_3_70.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_3_70.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_3_70.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_3_70.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_3_70.tif", 
                   river = "S1", 
                   discharge = 3.70)

S1_6_50 <- foen_hm(raster_path = "raster_files/S1_v_6_50.tif", 
                   base_flow = "raster_files/S1_v_6_50.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_6_50.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_6_50.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_6_50.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_6_50.tif", 
                   river = "S1", 
                   discharge = 6.50)

S1_8_50 <- foen_hm(raster_path = "raster_files/S1_v_8_50.tif", 
                   base_flow = "raster_files/S1_v_8_50.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_8_50.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_8_50.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_8_50.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_8_50.tif", 
                   river = "S1", 
                   discharge = 8.50)

S1_10_68 <- foen_hm(raster_path = "raster_files/S1_v_10_68.tif", 
                   base_flow = "raster_files/S1_v_10_68.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_10_68.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_10_68.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_10_68.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_10_68.tif", 
                   river = "S1", 
                   discharge = 10.68)

S1_13_00 <- foen_hm(raster_path = "raster_files/S1_v_13_00.tif", 
                   base_flow = "raster_files/S1_v_13_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_13_00.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_13_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_13_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_13_00.tif", 
                   river = "S1", 
                   discharge = 13.00)

S1_15_00 <- foen_hm(raster_path = "raster_files/S1_v_15_00.tif", 
                   base_flow = "raster_files/S1_v_15_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_15_00.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_15_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_15_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_15_00.tif", 
                   river = "S1", 
                   discharge = 15.00)

S1_18_00 <- foen_hm(raster_path = "raster_files/S1_v_18_00.tif", 
                   base_flow = "raster_files/S1_v_18_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_18_00.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_18_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_18_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_18_00.tif", 
                   river = "S1", 
                   discharge = 18.00)

S1_20_00 <- foen_hm(raster_path = "raster_files/S1_v_20_00.tif", 
                   base_flow = "raster_files/S1_v_20_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S1_foen_class_pers_20_00.tif", 
                   output_path_reclass =
                     "results_foen/S1_foen_class_20_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S1_foen_20_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S1_foen_pers_20_00.tif", 
                   river = "S1", 
                   discharge = 20.00)
```

## S2
```{r}
S2_2_00 <- foen_hm(raster_path = "raster_files/S2_v_2_00.tif", 
                   base_flow = "raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_2_00.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_2_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_2_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_2_00.tif", 
                   river = "S2", 
                   discharge = 2.00)

S2_3_20 <- foen_hm(raster_path = "raster_files/S2_v_3_20.tif", 
                   base_flow = "raster_files/S2_v_3_20.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_3_20.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_3_20.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_3_20.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_3_20.tif", 
                   river = "S2", 
                   discharge = 3.20)

S2_6_50 <- foen_hm(raster_path = "raster_files/S2_v_6_50.tif", 
                   base_flow = "raster_files/S2_v_6_50.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_6_50.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_6_50.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_6_50.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_6_50.tif", 
                   river = "S2", 
                   discharge = 6.50)

S2_8_50 <- foen_hm(raster_path = "raster_files/S2_v_8_50.tif", 
                   base_flow = "raster_files/S2_v_8_50.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_8_50.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_8_50.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_8_50.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_8_50.tif", 
                   river = "S2", 
                   discharge = 8.50)

S2_10_93 <- foen_hm(raster_path = "raster_files/S2_v_10_93.tif", 
                   base_flow = "raster_files/S2_v_10_93.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_10_93.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_10_93.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_10_93.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_10_93.tif", 
                   river = "S2", 
                   discharge = 10.93)

S2_13_00 <- foen_hm(raster_path = "raster_files/S2_v_13_00.tif", 
                   base_flow = "raster_files/S2_v_13_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_13_00.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_13_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_13_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_13_00.tif", 
                   river = "S2", 
                   discharge = 13.00)

S2_15_00 <- foen_hm(raster_path = "raster_files/S2_v_15_00.tif", 
                   base_flow = "raster_files/S2_v_15_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_15_00.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_15_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_15_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_15_00.tif", 
                   river = "S2", 
                   discharge = 15.00)

S2_18_00 <- foen_hm(raster_path = "raster_files/S2_v_18_00.tif", 
                   base_flow = "raster_files/S2_v_18_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_18_00.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_18_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_18_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_18_00.tif", 
                   river = "S2", 
                   discharge = 18.00)

S2_20_00 <- foen_hm(raster_path = "raster_files/S2_v_20_00.tif", 
                   base_flow = "raster_files/S2_v_20_00.tif",
                   output_path_pers_reclass =
                     "results_foen/S2_foen_class_pers_20_00.tif", 
                   output_path_reclass =
                     "results_foen/S2_foen_class_20_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/S2_foen_20_00.tif",
                   output_path_hm_persistent =
                     "results_foen/S2_foen_pers_20_00.tif", 
                   river = "S2", 
                   discharge = 20.00)
```


# * Thur
## TH4
```{r}
TH4_2_00 <- foen_hm(raster_path = "raster_files/TH4_v_2_00.tif", 
                   base_flow = "raster_files/TH4_v_2_00.tif",
                   output_path_pers_reclass =
                     "results_foen/TH4_foen_class_pers_2_00.tif", 
                   output_path_reclass =
                     "results_foen/TH4_foen_class_2_00.tif", 
                   HSC_path = "HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "results_foen/TH4_foen_2_00.tif",
                   output_path_hm_persistent =
                     "results_foen/TH4_foen_pers_2_00.tif", 
                   river = "TH4", 
                   discharge = 2.00)
```
11_45, 15_00, 18_00, 19_96, 22_50, 25_00, 27_00, 30_00, 32_93

# Vorderrhein
## VR3
```{r}

```
2_90, 6_00, 9_00, 12_00, 15_00, 18_80, 22_00, 25_00, 28_00, 31_00, 34_00, 37_00, 40_10, 43_00, 46_00, 48_00, 50_00, 52_90

# Bind Metric Results 
```{r}
# GL1 - ok
# GL2
# L2
# M1
# S1
# S2
# TH4
# VR3

# metrics
metric_results <- rbind(GL1_3_28$metrics, GL1_6_00$metrics, GL1_9_00$metrics, GL1_12_68$metrics, GL1_16_00$metrics,
                        GL1_19_00$metrics, GL1_22_00$metrics, GL1_25_00$metrics, GL1_28_00$metrics, GL1_31_76$metrics)

# safe df into .csv file
write.csv(metric_results, file = "results_foen/results_foen_metrics.csv", row.names = FALSE)

# GL1 
# GL2
# L2
# M1
# S1
# S2
# TH4
# VR3

# freq_tables
freq_tables <- rbind(L2_2$freq, L2_3$freq, L2_4$freq, L2_7$freq, L2_9$freq,
                     L2_11$freq, L2_13$freq, L2_15$freq, L2_18$freq)

# write data frame into .csv file
write.csv(freq_tables, file = "results_foen/results_foen_freq_tables.csv", row.names = FALSE)
```

# Extract/Rekonstruct Discharges
Idee: stacked raster für v und wd erstellen pro section, dann extract 
```{r}

```



