---
title: "Index_Calculation"
format: html
---

# Clean Environment
```{r}
#clear R environment -------------------------------------------
rm(list = ls())
```


# Libraries 
```{r}

# Load the required packages
library("dplyr")
library("readr")
library("tidyr")
library("tidyverse")
library("stringr")
library(gbm)
library(dismo)
library(raster)
```

# Load Data
## Lab Data
```{r}
lab <- read_delim("Data/abiotic_lab.csv")
```

# Prepare Data 
```{r}
# remove all response variables
lab_response <- lab[ , c(1:29)]

lab <- lab[ ,-c(1:29)]
```

# Calculate EPT Taxa 
```{r}
# Plecoptera, Trichoptera, Ephemeroptera
# Define the letter combination to search for
combination_Plecoptera <- "Plecoptera"
combination_Trichoptera <- "Trichoptera"
combination_Ephemeroptera <- "Ephemeroptera"

# Identify the column names containing the letter combination
matching_Plecoptera <- grep(combination_Plecoptera, names(lab), value = TRUE)
matching_Trichoptera <- grep(combination_Trichoptera, names(lab), value = TRUE)
matching_Ephemeroptera <- grep(combination_Ephemeroptera, names(lab), value = TRUE)


# Iterate through each row and count the cells meeting the conditions
lab$Count_Plecoptera <- apply(lab, 1, function(row) {
  sum(!is.na(row[matching_Plecoptera]) & row[matching_Plecoptera] > 0)
})

lab$Count_Trichoptera <- apply(lab, 1, function(row) {
  sum(!is.na(row[matching_Trichoptera]) & row[matching_Trichoptera] > 0)
})

lab$Count_Ephemeroptera <- apply(lab, 1, function(row) {
  sum(!is.na(row[matching_Ephemeroptera]) & row[matching_Ephemeroptera] > 0)
})

# Calculate EPT Taxa per Sampling_location 
lab$EPT_Taxa <- lab$Count_Plecoptera + lab$Count_Trichoptera + lab$Count_Ephemeroptera

# Display the resulting dataframe
print(lab$Count_Plecoptera) # - OK
print(lab$EPT_Taxa) # - OK?
```

# Calculate Shannon (H) Index & Abundance
```{r}
# Create a sample dataframe
lab_Shannon <- lab[ , -c(193:197)]

# Convert all columns to numeric format
lab_Shannon <- data.frame(sapply(lab_Shannon, as.numeric))

# Calculate the total number of observations at each sampling site
# df$total_count <- rowSums(df[, -1])
abundance <- rowSums(lab_Shannon, na.rm = TRUE) # = Abundance


# Calculate the proportion of each species within each sampling site
# proportions <- df[, -c(1, ncol(df))] / df$total_count
 proportions <- lab_Shannon[, -c(1, ncol(lab_Shannon))] / abundance

# Calculate the Shannon index for each sampling site
# shannon <- -rowSums(proportions * log2(proportions), na.rm = TRUE)
shannon <- -rowSums(proportions * log2(proportions), na.rm = TRUE)

# Compute the average Shannon index across all sampling sites
average_shannon <- mean(shannon, na.rm = TRUE)

# Display the results
print(shannon)
print(average_shannon)
```

# Calculate Number of Taxa 
```{r}
# Iterate through each row and count the cells meeting the conditions
Number_Taxa <- apply(lab_Shannon, 1, function(row) {
  sum(!is.na(row) & row > 0)
})
```

# Combine all Results in one DF
```{r}
# combine all results + response variables 
lab_new <- cbind(lab, shannon, Number_Taxa, abundance, lab_response)

# create clean df which only contains the values needed 
lab_index <- lab_new |>
  dplyr::select(EPT_Taxa, shannon, Number_Taxa, abundance, Water_depth_cm, `Flow_velocity_v60_cm/s`)
```

# Calculate K-Index (Theodoropoulos et al., 2018)
```{r}
lab_index <- lab_index |>
  mutate(k_index = 0.4*(Number_Taxa/max(Number_Taxa, na.rm = TRUE))
         + 0.3*(shannon/max(shannon, na.rm = TRUE))
         + 0.2*(EPT_Taxa/max(EPT_Taxa, na.rm = TRUE))
         + 0.1*(abundance/max(abundance, na.rm = TRUE))) |>
  dplyr::select(-EPT_Taxa, -shannon, -Number_Taxa, -abundance)

# export .csv for model 
write.csv(lab_index, "Data/Lab_k_index.csv")
```


