---
title: "Hydrodynamic_Model_Results"
format: html
---

# Load packages
```{r}
# clear R memory 
rm(list = ls())

# load packages 
pkgCheck <- function(x){ 
  if (!require(x,character.only = TRUE)){
    install.packages(x,dependencies=TRUE)
    if(!require(x,character.only = TRUE)) {
      stop()
    }
  }
}

pkgCheck("raster")
pkgCheck("spsurvey")
pkgCheck("terra")
pkgCheck("ggplot2")
pkgCheck("tibble")
pkgCheck("readr")
pkgCheck("dplyr")
pkgCheck("tidyr")
pkgCheck("scales")
pkgCheck("hdf5r")
pkgCheck("sp")
pkgCheck("sf")
pkgCheck("spatstat.geom")
pkgCheck("spatstat.explore")
pkgCheck("gstat")
pkgCheck("purrr")
pkgCheck("rgdal")

# load self-written functions 
source("mth_functions.R")
```

# Convert Hydrodynamic Model Results
## Glenner: GL1
```{r}
# Define the range of values for discharge and results_h5
h5_path_values <- c("hdm_models/GL1/results_GL1_3.28.h5", 
             "hdm_models/GL1/results_GL1_6.00.h5", 
             "hdm_models/GL1/results_GL1_9.00.h5", 
             "hdm_models/GL1/results_GL1_12.68.h5", 
             "hdm_models/GL1/results_GL1_16.00.h5", 
             "hdm_models/GL1/results_GL1_19.00.h5", 
             "hdm_models/GL1/results_GL1_22.00.h5", 
             "hdm_models/GL1/results_GL1_25.00.h5", 
             "hdm_models/GL1/results_GL1_28.00.h5", 
             "hdm_models/GL1/results_GL1_31.76.h5")
raster_v_path_vaLues <- c("raster_files/GL1_v_3.28.tif", 
                   "raster_files/GL1_v_6.00.tif", 
                   "raster_files/GL1_v_9.00.tif", 
                   "raster_files/GL1_v_12.68.tif", 
                   "raster_files/GL1_v_16.00.tif",  
                   "raster_files/GL1_v_19.00.tif", 
                   "raster_files/GL1_v_22.00.tif", 
                   "raster_files/GL1_v_25.00.tif", 
                   "raster_files/GL1_v_28.00.tif", 
                   "raster_files/GL1_v_31.76.tif")
raster_wd_path_values <- c("raster_files/GL1_wd_3.28.tif", 
                   "raster_files/GL1_wd_6.00.tif", 
                   "raster_files/GL1_wd_9.00.tif", 
                   "raster_files/GL1_wd_12.68.tif", 
                   "raster_files/GL1_wd_16.00.tif",  
                   "raster_files/GL1_wd_19.00.tif", 
                   "raster_files/GL1_wd_22.00.tif", 
                   "raster_files/GL1_wd_25.00.tif", 
                   "raster_files/GL1_wd_28.00.tif", 
                   "raster_files/GL1_wd_31.76.tif")
 

# Loop through the combinations of discharge and results_h5 values
for (i in seq_along(h5_path_values)) {
  for (j in seq_along(raster_v_path_vaLues)) {
    for (k in seq_along(raster_wd_path_values)) {
        hdm_results(
        h5_path = h5_path_values[i], 
        twodm_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm",
        shp_path = "raster_files/GL1_shape.shp", 
        raster_v_path = raster_v_path_vaLues[j],
        raster_wd_path = raster_wd_path_values[k])
  }
  }
}
```

## Landquart: L2
### Single Attribute Rasters
```{r}
# Define the range of values for discharge and results_h5
h5_path_values <- c("hdm_models/L2/results_L2_2.40.h5",
                    "hdm_models/L2/results_L2_3.90.h5",
                    "hdm_models/L2/results_L2_7.00.h5",
                    "hdm_models/L2/results_L2_9.24.h5",
                    "hdm_models/L2/results_L2_13.30.h5",
                    "hdm_models/L2/results_L2_16.50.h5",
                    "hdm_models/L2/results_L2_18.90.h5")
raster_v_path_vaLues <- c("raster_files/L2_v_2.40.tif",
                          "raster_files/L2_v_3.90.tif",
                          "raster_files/L2_v_7.00.tif",
                          "raster_files/L2_v_9.24.tif",
                          "raster_files/L2_v_13.30.tif",
                          "raster_files/L2_v_16.50.tif",
                          "raster_files/L2_v_18.90.tif")
raster_wd_path_values <- c("raster_files/L2_wd_2.40.tif",
                          "raster_files/L2_wd_3.90.tif",
                          "raster_files/L2_wd_7.00.tif",
                          "raster_files/L2_wd_9.24.tif",
                          "raster_files/L2_wd_13.30.tif",
                          "raster_files/L2_wd_16.50.tif",
                          "raster_files/L2_wd_18.90.tif")
 
# Create a flag to track if all values are simulated
all_simulated <- FALSE

# Loop through the combinations of discharge and results_h5 values
for (i in seq_along(h5_path_values)) {
  for (j in seq_along(raster_v_path_vaLues)) {
    for (k in seq_along(raster_wd_path_values)) {
        hdm_results(
        h5_path = h5_path_values[i], 
        twodm_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm",
        shp_path = "raster_files/L2_shape.shp", 
        raster_v_path = raster_v_path_vaLues[j],
        raster_wd_path = raster_wd_path_values[k])

      # Check if all values are simulated and exit the loop if true
    if (length(discharge_values)) {
      all_simulated <- TRUE
      break
    }
    }
    }
  
  
  # Check if all values are simulated and exit the loop if true
  if (all_simulated) {
    break
  }
  }
```


```{r}
# L2 with Q: 2.4 m3/s
L2_2 <- hdm_results(
  h5_path = "hdm_models/L2/results_L2_2.40.h5", 
  twodm_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_2.40.tif",
  raster_wd_path = "raster_files/L2_wd_2.40.tif")

GL1_1 <- hdm_results(
  h5_path = "hdm_models/GL1/results_GL1_3.28.h5", 
  twodm_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm",
  shp_path = "raster_files/GL1_shape.shp", 
  raster_v_path = "raster_files/GL1_v_3.28.tif",
  raster_wd_path = "raster_files/GL1_v_3.28.tif")

# L2 with Q: 3.9 m3/s
L2_3 <- hdm_results(
  h5_path = "hdm_results/results_3.9_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_3.tif",
  raster_wd_path = "raster_files/L2_wd_3.tif")

# L2 with Q: 4.6 m3/s
L2_4 <- hdm_results(
  h5_path = "hdm_results/results_4.6_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_4.tif",
  raster_wd_path = "raster_files/L2_wd_4.tif")

# L2 with Q: 7 m3/s
L2_7 <- hdm_results(
  h5_path = "hdm_results/results_7_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_7.tif",
  raster_wd_path = "raster_files/L2_wd_7.tif")

# L2 with Q: 9.24 m3/s
L2_9 <- hdm_results(
  h5_path = "hdm_results/results_9.24_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_9.tif",
  raster_wd_path = "raster_files/L2_wd_9.tif")

# L2 with Q: 11.4 m3/s
L2_11 <- hdm_results(
  h5_path = "hdm_results/results_11.4_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_11.tif",
  raster_wd_path = "raster_files/L2_wd_11.tif")

# L2 with Q: 13.3 m3/s
L2_13 <- hdm_results(
  h5_path = "hdm_results/results_13.3_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_13.tif",
  raster_wd_path = "raster_files/L2_wd_13.tif")

# L2 with Q: 15 m3/s
L2_15 <- hdm_results(
  h5_path = "hdm_results/results_15_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_15.tif",
  raster_wd_path = "raster_files/L2_wd_15.tif")

# L2 with Q: 18.9 m3/s
L2_18 <- hdm_results(
  h5_path = "hdm_results/results_18.9_L2.h5", 
  twodm_path = "hdm_results/L2_mesh.2dm",
  shp_path = "raster_files/L2_shape.shp", 
  raster_v_path = "raster_files/L2_v_18.tif",
  raster_wd_path = "raster_files/L2_wd_18.tif")
```

### Stacked Rasters 
```{r}
# L2 with Q: 2.4 m3/s
stack_raster(v_path = "raster_files/L2_v_2.tif",
             wd_path = "raster_files/L2_wd_2.tif",
             stack_path = "rasters_stacked/L2_2.grd")

# L2 with Q: 3.9 m3/s
stack_raster(v_path = "raster_files/L2_v_3.tif",
             wd_path = "raster_files/L2_wd_3.tif",
             stack_path = "rasters_stacked/L2_3.grd")

# L2 with Q: 4.6 m3/s
stack_raster(v_path = "raster_files/L2_v_4.tif",
             wd_path = "raster_files/L2_wd_4.tif",
             stack_path = "rasters_stacked/L2_4.grd")

# L2 with Q: 7 m3/s
stack_raster(v_path = "raster_files/L2_v_7.tif",
             wd_path = "raster_files/L2_wd_7.tif",
             stack_path = "rasters_stacked/L2_7.grd")

# L2 with Q: 9.24 m3/s
stack_raster(v_path = "raster_files/L2_v_9.tif",
             wd_path = "raster_files/L2_wd_9.tif",
             stack_path = "rasters_stacked/L2_9.grd")

# L2 with Q: 11.4 m3/s
stack_raster(v_path = "raster_files/L2_v_11.tif",
             wd_path = "raster_files/L2_wd_11.tif",
             stack_path = "rasters_stacked/L2_11.grd")

# L2 with Q: 13.3 m3/s
stack_raster(v_path = "raster_files/L2_v_13.tif",
             wd_path = "raster_files/L2_wd_13.tif",
             stack_path = "rasters_stacked/L2_13.grd")

# L2 with Q: 15 m3/s
stack_raster(v_path = "raster_files/L2_v_15.tif",
             wd_path = "raster_files/L2_wd_15.tif",
             stack_path = "rasters_stacked/L2_15.grd")

# L2 with Q: 18.9 m3/s
stack_raster(v_path = "raster_files/L2_v_18.tif",
             wd_path = "raster_files/L2_wd_18.tif",
             stack_path = "rasters_stacked/L2_18.grd")
```


## Moesa: MR
```{r}
```

## Moesa: M1
```{r}
```


