---
title: "basement_function"
format: html
---
```{r}
rm(list = ls())

# load all Packages ---
library(hdf5r)
library(sp)
library(sf)
library(ggplot2)
library(dplyr)
library(readr)
library(Metrics)
library(raster)
library(rgeos)
library(hydroGOF)
library(jsonlite)
```

# function
```{r}
basement <- function(model_json, model_new, mesh_path, simulation_json, simulation_new, setup_h5, results_h5, results_xdmf, results_json, discharge, strickler, time_end){

#read in model json
model <- fromJSON(model_json)

#modify it
#change mesh
model$SETUP$DOMAIN$BASEPLANE_2D$GEOMETRY$mesh_file <- mesh_path

 #change names
  ifelse(model$SETUP$DOMAIN$BASEPLANE_2D$GEOMETRY$STRINGDEF$name[1] == "input", 
         model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$name[1] <- "input", 
         model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$name[1] <- "output") 
  
 #change names
  ifelse(model$SETUP$DOMAIN$BASEPLANE_2D$GEOMETRY$STRINGDEF$name[2] == "output", 
         model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$name[2] <- "output", 
         model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$name[2] <- "input") 
  
    #change discharge
  ifelse(model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$name[1] == "input", 
         model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$discharge[1] <- discharge, 
         model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$discharge[1] <- NA) 


#change Strickler
model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$FRICTION$default_friction <- strickler

#export 
model_exp <- toJSON(model, pretty = TRUE, auto_unbox = TRUE)
write(model_exp, model_new)

#read in simulation json
simulation <- fromJSON(simulation_json)

#modify it
simulation$SIMULATION$TIME$end <- time_end

#export 
simulation_exp <- toJSON(simulation, pretty = TRUE, auto_unbox = TRUE)
write(simulation_exp, simulation_new)

# Set up BASEMENT
setup_cmd_name <- "c:\\Programme\\BASEMENT 3.2.0\\bin\\BMv3_BASEplane_setup.exe"
  setup_param1 = paste("-f ", getwd(), "\\", model_new, sep="")
  setup_param2 = paste("-o ", getwd(), "\\", setup_h5, sep="")
  system2(setup_cmd_name, args = c(setup_param1, setup_param2))
  
  # Simulation in BASEMENT
simulation_cmd_name <- "c:\\Programme\\BASEMENT 3.2.0\\bin\\BMv3_BASEplane_cudaC.exe"
  simulation_param1 = paste("-f ", getwd(), "\\", simulation_new, sep="")
  simulation_param2 = paste("-r ", getwd(), "\\", setup_h5, sep="")
  simulation_param3 = paste("-o ", getwd(), "\\", results_h5,  sep="")
  system2(simulation_cmd_name, args = c(simulation_param1, simulation_param2, simulation_param3, "-p"))

  # Results of BASEMENT
results_cmd_name <- "c:\\Programme\\BASEMENT 3.2.0\\bin\\BMv3_BASEplane_results.exe"
  results_param1 = paste("-f ", getwd(), "\\", results_json, sep="")
  results_param2 = paste("-r ", getwd(), "\\", results_h5, sep="")
  results_param3 = paste("-o ", getwd(), "\\", results_xdmf, sep="")
  system2(results_cmd_name, args = c(results_param1, results_param2, results_param3))
}
```


# Test-Application of function 
```{r}
GL2_3_21 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_3_21.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_3_21",
             results_json = "hdm_models/GL2/results.json",
             discharge = 3.21, 
             strickler = 38, 
             time_end = 3600)

L2_2_40 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_2_40.h5",
                     results_xdmf = "hdm_models/L2/results_L2_2_40",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 2.40, 
                     strickler = 11.5,
                     time_end = 3600)
```


