---
title: "Reconstruct Discharges of Sampling Days"
format: html
---

# Load packages
```{r}
# clear R memory 
rm(list = ls())

# load packages 
pkgCheck <- function(x){ 
  if (!require(x,character.only = TRUE)){
    install.packages(x,dependencies=TRUE)
    if(!require(x,character.only = TRUE)) {
      stop()
    }
  }
}

pkgCheck("raster")
pkgCheck("spsurvey")
pkgCheck("terra")
pkgCheck("ggplot2")
pkgCheck("tibble")
pkgCheck("readr")
pkgCheck("dplyr")
pkgCheck("tidyr")
pkgCheck("scales")
pkgCheck("hdf5r")
pkgCheck("sp")
pkgCheck("sf")
pkgCheck("spatstat.geom")
pkgCheck("spatstat.explore")
pkgCheck("gstat")
pkgCheck("purrr")
pkgCheck("rgdal")

# load self-written functions 
source("mth_functions.R")
```


## Read/prepare .csv files
```{r}
mzb_data <- read_delim("abiotic_mi_sampling/Abiotic_MI_Lab.csv")

data <- mzb_data |>
  select(x, y, Reach_Untersuchungsstelle, `Flow_velocity_v60_cm/s`, Water_depth_cm, join_key) |>
  rename(reach = Reach_Untersuchungsstelle,
         velocity = `Flow_velocity_v60_cm/s`,
         depth = Water_depth_cm)

# select only single river sections 
data_GL1 <- data |>
  subset(reach == "GL1") |>
  mutate(x = as.numeric(x),
         y = as.numeric(y)) |>
  select(x, y)

data_GL1_add <- data |>
  subset(reach == "GL1") |>
  select(reach, velocity, depth, join_key)

data_GL2 <- data |>
  subset(reach == "GL2")|>
  mutate(x = as.numeric(x),
         y = as.numeric(y)) |>
  select(x, y)

data_GL2_add <- data |>
  subset(reach == "GL2") |>
  select(reach, velocity, depth, join_key)

data_L2 <- data |>
  subset(reach == "L2")

data_M1 <- data |>
  subset(reach == "M1")

data_S1 <- data |>
  subset(reach == "S1")

data_S2 <- data |>
  subset(reach == "S2")

data_TH4 <- data |>
  subset(reach == "TH4")

data_VR3 <- data |>
  subset(reach == "VR3")
```


## Glenner: GL1
```{r}
# read raster files (wd + v per discharge)
GL1_v_3_28 <- raster("raster_files/GL1_v_3_28.tif")
GL1_wd_3_28 <- raster("raster_files/GL1_wd_3_28.tif")

GL1_v_6_00 <- raster("raster_files/GL1_v_6_00.tif")
GL1_wd_6_00 <- raster("raster_files/GL1_wd_6_00.tif")

GL1_v_9_00 <- raster("raster_files/GL1_v_9_00.tif")
GL1_wd_9_00 <- raster("raster_files/GL1_wd_9_00.tif")

GL1_v_12_68 <- raster("raster_files/GL1_v_12_68.tif")
GL1_wd_12_68 <- raster("raster_files/GL1_wd_12_68.tif")

GL1_v_16_00 <- raster("raster_files/GL1_v_16_00.tif")
GL1_wd_16_00 <- raster("raster_files/GL1_wd_16_00.tif")

GL1_v_19_00 <- raster("raster_files/GL1_v_19_00.tif")
GL1_wd_19_00 <- raster("raster_files/GL1_wd_19_00.tif")

GL1_v_22_00 <- raster("raster_files/GL1_v_22_00.tif")
GL1_wd_22_00 <- raster("raster_files/GL1_wd_22_00.tif")

GL1_v_25_00 <- raster("raster_files/GL1_v_25_00.tif")
GL1_wd_25_00 <- raster("raster_files/GL1_wd_25_00.tif")

GL1_v_28_00 <- raster("raster_files/GL1_v_28_00.tif")
GL1_wd_28_00 <- raster("raster_files/GL1_wd_28_00.tif")

GL1_v_31_76 <- raster("raster_files/GL1_v_31_76.tif")
GL1_wd_31_76 <- raster("raster_files/GL1_wd_31_76.tif")


# stack all rasters into one stack
GL1_stacked <- stack(GL1_v_3_28, GL1_wd_3_28, GL1_v_6_00, GL1_wd_6_00, GL1_v_9_00, GL1_wd_9_00, GL1_v_12_68, GL1_wd_12_68, GL1_v_16_00, GL1_wd_16_00, GL1_v_19_00, GL1_wd_19_00, GL1_v_22_00, GL1_wd_22_00, GL1_v_25_00, GL1_wd_25_00, GL1_v_28_00, GL1_wd_28_00, GL1_v_31_76, GL1_wd_31_76)

crs(GL1_stacked) <- "EPSG: 2056"

# check if rasters are correct
plot(GL1_stacked)

# write stacked raster 
writeRaster(GL1_stacked, "rasters_stacked/GL1_stacked.grd", overwrite = TRUE)
```

### create Plot df
```{r}
# read stacked raster
GL1_stacked <- stack("rasters_stacked/GL1_stacked.grd")

# extract velocity and water depth information for plots 
GL1_extract <- terra::extract(GL1_stacked, data_GL1) |>
  cbind(data_GL1_add) |>
  mutate(depth_measured = depth/100,
         velocity_measured = velocity/100)

# extract only measured values 
GL1_measured <- GL1_extract[, c(24:26)] 

# create long table with velocity values from rasters
GL1_v <- GL1_extract[ ,c(1,3,5,7,9,11,13,15,17,19, 24)] |>
  pivot_longer(cols = c(1:10),names_to = "discharge_v",
               values_to = "velocity")

# create long table with water depth values from rasters
GL1_wd <- GL1_extract[ ,c(2,4,6,8,10,12,14,16,18,20,24)] |>
  pivot_longer(cols = c(1:10),names_to = "discharge",
               values_to = "water_depth")

GL1_wd$discharge <- gsub("GL1_wd_", "", GL1_wd$discharge)
GL1_wd$discharge <- gsub("_", ".", GL1_wd$discharge)
GL1_wd$discharge <- as.numeric(GL1_wd$discharge)

GL1_plot <- GL1_wd |>
  full_join(GL1_v, by = "join_key") |>
  select(discharge, water_depth, velocity, join_key) |>
  full_join(GL1_measured, by = "join_key")
```


### Plot 
```{r}
ggplot(GL1_plot, aes(discharge, water_depth, col = join_key)) +
  geom_point() +
  geom_point(data = GL1_plot, aes(y = depth_measured), col = "blue") +
  ggtitle(" ") 

lineplot <- ggplot(GL1_plot, aes(discharge, water_depth, col = join_key)) +
  geom_line()

# extract information from plot
data_from_scatterplot <- ggplot_build(lineplot)
data_from_scatterplot$data[[1]]
```


## Glenner: GL2
```{r}
# read stacked rasters (wd + v per discharge)
GL2_v_3_21 <- raster("raster_files/GL2_v_3_21.tif")
GL2_wd_3_21 <- raster("raster_files/GL2_wd_3_21.tif")

GL2_v_6_00 <- raster("raster_files/GL2_v_6_00.tif")
GL2_wd_6_00 <- raster("raster_files/GL2_wd_6_00.tif")

GL2_v_9_00 <- raster("raster_files/GL2_v_9_00.tif")
GL2_wd_9_00 <- raster("raster_files/GL2_wd_9_00.tif")

GL2_v_11_00 <- raster("raster_files/GL2_v_11_00.tif")
GL2_wd_11_00 <- raster("raster_files/GL2_wd_11_00.tif")

GL2_v_12_52 <- raster("raster_files/GL2_v_12_52.tif")
GL2_wd_12_52 <- raster("raster_files/GL2_wd_12_52.tif")

GL2_v_16_00 <- raster("raster_files/GL2_v_16_00.tif")
GL2_wd_16_00 <- raster("raster_files/GL2_wd_16_00.tif")

GL2_v_19_00 <- raster("raster_files/GL2_v_19_00.tif")
GL2_wd_19_00 <- raster("raster_files/GL2_wd_19_00.tif")

GL2_v_22_00 <- raster("raster_files/GL2_v_22_00.tif")
GL2_wd_22_00 <- raster("raster_files/GL2_wd_22_00.tif")

GL2_v_25_00 <- raster("raster_files/GL2_v_25_00.tif")
GL2_wd_25_00 <- raster("raster_files/GL2_wd_25_00.tif")

GL2_v_28_00 <- raster("raster_files/GL2_v_28_00.tif")
GL2_wd_28_00 <- raster("raster_files/GL2_wd_28_00.tif")

GL2_v_31_53 <- raster("raster_files/GL2_v_31_53.tif")
GL2_wd_31_53 <- raster("raster_files/GL2_wd_31_53.tif")


# stack rasters into one stack
GL2_stacked <- stack(GL2_v_3_21, GL2_wd_3_21, GL2_v_6_00, GL2_wd_6_00, GL2_v_9_00, GL2_wd_9_00, GL2_v_11_00, GL2_wd_11_00, GL2_v_12_52, GL2_wd_12_52, GL2_v_16_00, GL2_wd_16_00, GL2_v_19_00, GL2_wd_19_00, GL2_v_22_00, GL2_wd_22_00, GL2_v_25_00, GL2_wd_25_00, GL2_v_28_00, GL2_wd_28_00, GL2_v_31_53, GL2_wd_31_53)

crs(GL2_stacked) <- "EPSG: 2056"

plot(GL2_stacked$GL2_v_25_00)


# write stacked raster 
writeRaster(GL2_stacked, "rasters_stacked/GL2_stacked.grd", overwrite = TRUE)
```

### create Plot df
```{r}
# read stacked raster
GL2_stacked <- stack("rasters_stacked/GL2_stacked.grd")

# extract velocity and water depth information for plots 
GL2_extract <- terra::extract(GL2_stacked, data_GL2) |>
  cbind(data_GL2_add) |>
  mutate(depth = depth/100,
         velocity = velocity/100)

# create long table with velocity values from rasters
GL2_v <- GL2_extract[ ,c(1,3,5,7,9,11,13,15,17,19,22)] |>
  pivot_longer(cols = c(1:10),names_to = "discharge_v",
               values_to = "velocity_v")

# create long table with water depth values from rasters
GL2_wd <- GL2_extract[ ,c(2,4,6,8,10,12,14,16,18,20,22,23)] |>
  pivot_longer(cols = c(1:10),names_to = "discharge",
               values_to = "water_depth")

#GL1_wd$discharge <- gsub("GL1_wd_", "", GL1_wd$discharge)
#GL1_wd$discharge <- gsub("_", ".", GL1_wd$discharge)
#GL1_wd$discharge <- as.numeric(GL1_wd$discharge)

#GL1_plot <- cbind(GL1_wd, GL1_v) |>
#  select(discharge, water_depth, velocity)
```


## Landquart: L2
```{r}
# read stacked rasters (wd + v per discharge)
L2_v_2_40 <- raster("raster_files/L2_v_2_40.tif")
L2_wd_2_40 <- raster("raster_files/L2_wd_2_40.tif")

L2_v_3_90 <- raster("raster_files/L2_v_3_90.tif")
L2_wd_3_90 <- raster("raster_files/L2_wd_3_90.tif")

L2_v_7_00 <- raster("raster_files/L2_v_7_00.tif")
L2_wd_7_00 <- raster("raster_files/L2_wd_7_00.tif")

L2_v_9_24 <- raster("raster_files/L2_v_9_24.tif")
L2_wd_9_24 <- raster("raster_files/L2_wd_9_24.tif")

L2_v_13_30 <- raster("raster_files/L2_v_13_30.tif")
L2_wd_13_30 <- raster("raster_files/L2_wd_13_30.tif")

L2_v_16_50 <- raster("raster_files/L2_v_16_50.tif")
L2_wd_16_50 <- raster("raster_files/L2_wd_16_50.tif")

L2_v_18_90 <- raster("raster_files/L2_v_18_90.tif")
L2_wd_18_90 <- raster("raster_files/L2_wd_18_90.tif")


# stack rasters into one stack
L2_stacked <- stack(L2_v_2_40, L2_wd_2_40, L2_v_3_90, L2_wd_3_90, L2_v_7_00, L2_wd_7_00, L2_v_9_24, L2_wd_9_24, L2_v_13_30, L2_wd_13_30, L2_v_16_50, L2_wd_16_50, L2_v_18_90, L2_wd_18_90)

# check if rasters are correct
plot(L2_stacked)

# write stacked raster 
writeRaster(L2_stacked, "rasters_stacked/L2_stacked.grd", overwrite = TRUE)
```

## Moesa: M1
```{r}
# read stacked rasters (wd + v per discharge)
M1_v_0_47 <- raster("raster_files/M1_v_0_47.tif")
M1_wd_0_47 <- raster("raster_files/M1_wd_0_47.tif")

M1_v_0_60 <- raster("raster_files/M1_v_0_60.tif")
M1_wd_0_60 <- raster("raster_files/M1_wd_0_60.tif")

M1_v_4_00 <- raster("raster_files/M1_v_4_00.tif")
M1_wd_4_00 <- raster("raster_files/M1_wd_4_00.tif")

M1_v_6_00 <- raster("raster_files/M1_v_6_00.tif")
M1_wd_6_00 <- raster("raster_files/M1_wd_6_00.tif")

M1_v_8_00 <- raster("raster_files/M1_v_8_00.tif")
M1_wd_8_00 <- raster("raster_files/M1_wd_8_00.tif")

M1_v_10_00 <- raster("raster_files/M1_v_10_00.tif")
M1_wd_10_00 <- raster("raster_files/M1_wd_10_00.tif")

M1_v_12_00 <- raster("raster_files/M1_v_12_00.tif")
M1_wd_12_00 <- raster("raster_files/M1_wd_12_00.tif")

M1_v_14_00 <- raster("raster_files/M1_v_14_00.tif")
M1_wd_14_00 <- raster("raster_files/M1_wd_14_00.tif")

M1_v_16_00 <- raster("raster_files/M1_v_16_00.tif")
M1_wd_16_00 <- raster("raster_files/M1_wd_16_00.tif")

M1_v_18_84 <- raster("raster_files/M1_v_18_84.tif")
M1_wd_18_84 <- raster("raster_files/M1_wd_18_84.tif")

M1_v_22_84 <- raster("raster_files/M1_v_22_84.tif")
M1_wd_22_84 <- raster("raster_files/M1_wd_22_84.tif")


# stack all rasters into one stack
M1_stacked <- stack(M1_v_0_47, M1_wd_0_47, M1_v_0_60, M1_wd_0_60, M1_v_4_00, M1_wd_4_00, M1_v_6_00, M1_wd_6_00, M1_v_8_00, M1_wd_8_00, M1_v_10_00, M1_wd_10_00, M1_v_12_00, M1_wd_12_00, M1_v_14_00, M1_wd_14_00, M1_v_16_00, M1_wd_16_00, M1_v_18_84, M1_wd_18_84, M1_v_22_84, M1_wd_22_84)

# check if rasters are correct
plot(M1_stacked)

# write stacked raster 
writeRaster(M1_stacked, "rasters_stacked/M1_stacked.grd", overwrite = TRUE)
```

## Sitter: S1
```{r}
# read stacked rasters (wd + v per discharge)
S1_v_2_00 <- raster("raster_files/S1_v_2_00.tif")
S1_wd_2_00 <- raster("raster_files/S1_wd_2_00.tif")

S1_v_3_70 <- raster("raster_files/S1_v_3_70.tif")
S1_wd_3_70 <- raster("raster_files/S1_wd_3_70.tif")

S1_v_6_50 <- raster("raster_files/S1_v_6_50.tif")
S1_wd_6_50 <- raster("raster_files/S1_wd_6_50.tif")

S1_v_8_50 <- raster("raster_files/S1_v_8_50.tif")
S1_wd_8_50 <- raster("raster_files/S1_wd_8_50.tif")

S1_v_10_68 <- raster("raster_files/S1_v_10_68.tif")
S1_wd_10_68 <- raster("raster_files/S1_wd_10_68.tif")

S1_v_13_00 <- raster("raster_files/S1_v_13_00.tif")
S1_wd_13_00 <- raster("raster_files/S1_wd_13_00.tif")

S1_v_15_00 <- raster("raster_files/S1_v_15_00.tif")
S1_wd_15_00 <- raster("raster_files/S1_wd_15_00.tif")

S1_v_18_00 <- raster("raster_files/S1_v_18_00.tif")
S1_wd_18_00 <- raster("raster_files/S1_wd_18_00.tif")

S1_v_20_00 <- raster("raster_files/S1_v_20_00.tif")
S1_wd_20_00 <- raster("raster_files/S1_wd_20_00.tif")


# stack all rasters into one stack
S1_stacked <- stack(S1_v_2_00, S1_wd_2_00, S1_v_3_70, S1_wd_3_70, S1_v_6_50, S1_wd_6_50, S1_v_8_50, S1_wd_8_50, S1_v_10_68, S1_wd_10_68, S1_v_13_00, S1_wd_13_00, S1_v_15_00, S1_wd_15_00, S1_v_18_00, S1_wd_18_00, S1_v_20_00, S1_wd_20_00)

# check if rasters are correct
plot(S1_stacked$S1_v_20_00)

# write stacked raster 
writeRaster(S1_stacked, "rasters_stacked/S1_stacked.grd", overwrite = TRUE)
```

## Sitter: S2
```{r}
# read stacked rasters (wd + v per discharge)
S2_v_2_00 <- raster("raster_files/S2_v_2_00.tif")
S2_wd_2_00 <- raster("raster_files/S2_wd_2_00.tif")

S2_v_3_20 <- raster("raster_files/S2_v_3_20.tif")
S2_wd_3_20 <- raster("raster_files/S2_wd_3_20.tif")

S2_v_6_50 <- raster("raster_files/S2_v_6_50.tif")
S2_wd_6_50 <- raster("raster_files/S2_wd_6_50.tif")

S2_v_8_50 <- raster("raster_files/S2_v_8_50.tif")
S2_wd_8_50 <- raster("raster_files/S2_wd_8_50.tif")

S2_v_10_93 <- raster("raster_files/S2_v_10_93.tif")
S2_wd_10_93 <- raster("raster_files/S2_wd_10_93.tif")

S2_v_13_00 <- raster("raster_files/S2_v_13_00.tif")
S2_wd_13_00 <- raster("raster_files/S2_wd_13_00.tif")

S2_v_15_00 <- raster("raster_files/S2_v_15_00.tif")
S2_wd_15_00 <- raster("raster_files/S2_wd_15_00.tif")

S2_v_18_00 <- raster("raster_files/S2_v_18_00.tif")
S2_wd_18_00 <- raster("raster_files/S2_wd_18_00.tif")

S2_v_20_00 <- raster("raster_files/S2_v_20_00.tif")
S2_wd_20_00 <- raster("raster_files/S2_wd_20_00.tif")


# stack all rasters into one stack
S2_stacked <- stack(S2_v_2_00, S2_wd_2_00, S2_v_3_20, S2_wd_3_20, S2_v_6_50, S2_wd_6_50, S2_v_8_50, S2_wd_8_50, S2_v_10_93, S2_wd_10_93, S2_v_13_00, S2_wd_13_00, S2_v_15_00, S2_wd_15_00, S2_v_18_00, S2_wd_18_00, S2_v_20_00, S2_wd_20_00)

# check if rasters are correct
plot(S2_stacked$S2_wd_20_00)

# write stacked raster 
writeRaster(S2_stacked, "rasters_stacked/S2_stacked.grd", overwrite = TRUE)
```

## Thur: TH4
```{r}
# read stacked rasters (wd + v per discharge)
TH4_v_11_45 <- raster("raster_files/TH4_v_11_45.tif")
TH4_wd_11_45 <- raster("raster_files/TH4_wd_11_45.tif")

TH4_v_15_00 <- raster("raster_files/TH4_v_15_00.tif")
TH4_wd_15_00 <- raster("raster_files/TH4_wd_15_00.tif")

TH4_v_18_00 <- raster("raster_files/TH4_v_18_00.tif")
TH4_wd_18_00 <- raster("raster_files/TH4_wd_18_00.tif")

TH4_v_19_96 <- raster("raster_files/TH4_v_19_96.tif")
TH4_wd_19_96 <- raster("raster_files/TH4_wd_19_96.tif")

TH4_v_22_50 <- raster("raster_files/TH4_v_22_50.tif")
TH4_wd_22_50 <- raster("raster_files/TH4_wd_22_50.tif")

TH4_v_25_00 <- raster("raster_files/TH4_v_25_00.tif")
TH4_wd_25_00 <- raster("raster_files/TH4_wd_25_00.tif")

TH4_v_27_00 <- raster("raster_files/TH4_v_27_00.tif")
TH4_wd_27_00 <- raster("raster_files/TH4_wd_27_00.tif")

TH4_v_30_00 <- raster("raster_files/TH4_v_30_00.tif")
TH4_wd_30_00 <- raster("raster_files/TH4_wd_30_00.tif")

TH4_v_32_93 <- raster("raster_files/TH4_v_32_93.tif")
TH4_wd_32_93 <- raster("raster_files/TH4_wd_32_93.tif")

# stack all rasters into one stack
TH4_stacked <- stack(TH4_v_11_45, TH4_wd_11_45, TH4_v_15_00, TH4_wd_15_00, TH4_v_18_00, TH4_wd_18_00, TH4_v_19_96, TH4_wd_19_96, TH4_v_22_50, TH4_wd_22_50, TH4_v_25_00, TH4_wd_25_00, TH4_v_27_00, TH4_wd_27_00, TH4_v_30_00, TH4_wd_30_00, TH4_v_32_93, TH4_wd_32_93)

# check if rasters are correct
plot(TH4_stacked)

# write stacked raster 
writeRaster(TH4_stacked, "rasters_stacked/TH4_stacked.grd", overwrite = TRUE)
```

## Vorderrhein: VR3
```{r}
# read stacked rasters (wd + v per discharge)
VR3_v_2_90 <- raster("raster_files/VR3_v_2_90.tif")
VR3_wd_2_90 <- raster("raster_files/VR3_wd_2_90.tif")

VR3_v_6_00 <- raster("raster_files/VR3_v_6_00.tif")
VR3_wd_6_00 <- raster("raster_files/VR3_wd_6_00.tif")

VR3_v_9_00 <- raster("raster_files/VR3_v_9_00.tif")
VR3_wd_9_00 <- raster("raster_files/VR3_wd_9_00.tif")

VR3_v_12_00 <- raster("raster_files/VR3_v_12_00.tif")
VR3_wd_12_00 <- raster("raster_files/VR3_wd_12_00.tif")

VR3_v_15_00 <- raster("raster_files/VR3_v_15_00.tif")
VR3_wd_15_00 <- raster("raster_files/VR3_wd_15_00.tif")

VR3_v_18_80 <- raster("raster_files/VR3_v_18_80.tif")
VR3_wd_18_80 <- raster("raster_files/VR3_wd_18_80.tif")

VR3_v_22_00 <- raster("raster_files/VR3_v_22_00.tif")
VR3_wd_22_00 <- raster("raster_files/VR3_wd_22_00.tif")

VR3_v_25_00 <- raster("raster_files/VR3_v_25_00.tif")
VR3_wd_25_00 <- raster("raster_files/VR3_wd_25_00.tif")

VR3_v_28_00 <- raster("raster_files/VR3_v_28_00.tif")
VR3_wd_28_00 <- raster("raster_files/VR3_wd_28_00.tif")

VR3_v_31_00 <- raster("raster_files/VR3_v_31_00.tif")
VR3_wd_31_00 <- raster("raster_files/VR3_wd_31_00.tif")

VR3_v_34_00 <- raster("raster_files/VR3_v_34_00.tif")
VR3_wd_34_00 <- raster("raster_files/VR3_wd_34_00.tif")

VR3_v_37_00 <- raster("raster_files/VR3_v_37_00.tif")
VR3_wd_37_00 <- raster("raster_files/VR3_wd_37_00.tif")

VR3_v_40_10 <- raster("raster_files/VR3_v_40_10.tif")
VR3_wd_40_10 <- raster("raster_files/VR3_wd_40_10.tif")

VR3_v_43_00 <- raster("raster_files/VR3_v_43_00.tif")
VR3_wd_43_00 <- raster("raster_files/VR3_wd_43_00.tif")

VR3_v_46_00 <- raster("raster_files/VR3_v_46_00.tif")
VR3_wd_46_00 <- raster("raster_files/VR3_wd_46_00.tif")

VR3_v_48_00 <- raster("raster_files/VR3_v_48_00.tif")
VR3_wd_48_00 <- raster("raster_files/VR3_wd_48_00.tif")

VR3_v_50_00 <- raster("raster_files/VR3_v_50_00.tif")
VR3_wd_50_00 <- raster("raster_files/VR3_wd_50_00.tif")

VR3_v_52_90 <- raster("raster_files/VR3_v_52_90.tif")
VR3_wd_52_90 <- raster("raster_files/VR3_wd_52_90.tif")


# stack all rasters into one stack
VR3_stacked <- stack(VR3_v_2_90, VR3_wd_2_90, VR3_v_6_00, VR3_wd_6_00, VR3_v_9_00, VR3_wd_9_00, VR3_v_12_00, VR3_wd_12_00, VR3_v_15_00, VR3_wd_15_00, VR3_v_18_80, VR3_wd_18_80, VR3_v_22_00, VR3_wd_22_00, VR3_v_25_00, VR3_wd_25_00, VR3_v_28_00, VR3_wd_28_00, VR3_v_31_00, VR3_wd_31_00, VR3_v_34_00, VR3_wd_34_00, VR3_v_37_00, VR3_wd_37_00, VR3_v_40_10, VR3_wd_40_10, VR3_v_43_00, VR3_wd_43_00, VR3_v_46_00, VR3_wd_46_00, VR3_v_48_00, VR3_wd_48_00, VR3_v_50_00, VR3_wd_50_00, VR3_v_52_90, VR3_wd_52_90)

# check if rasters are correct
plot(VR3_stacked)

# write stacked raster 
writeRaster(VR3_stacked, "rasters_stacked/VR3_stacked.grd", overwrite = TRUE)
```