---
title: "test"
format: html
editor: visual
---

```{r}
rm(list = ls())

# load all Packages ---
library(hdf5r)
library(sp)
library(sf)
library(ggplot2)
library(dplyr)
library(readr)
library(Metrics)
library(raster)
library(rgeos)
library(hydroGOF)
library(jsonlite)

source("R2bas_func.r")

# set working directory ------
# setwd("u:/MZB/03_modelle/7_glenner/GL2/3_basement")
```

```{r}
#paths------
#INPUT
#model json path
model_json <- "hdm_models/GL1/model.json"
#simulation json path
simulation_json <- "hdm_models/GL1/simulation.json"
results_json <- "hdm_models/GL1/results.json"
#OUTPUT
setup_h5 <- "hdm_models/GL1/setup.h5"
results_h5 <- "hdm_models/GL1/results_3_28.h5"
#this can actually remain always the same
results_xdmf <- "hdm_models/GL1/results_3_28"

#read in model json
model <- fromJSON(model_json)

#modify it
#change mesh
mesh_path <- "U:/MZB/03_modelle/7_glenner/GL2/3_basement/Gl2_computational-mesh_gcp2_mod.2dm"
model$SETUP$DOMAIN$BASEPLANE_2D$GEOMETRY$mesh_file <- mesh_path

#change discharge
model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$discharge[1] <- 3.28

#change Strickler
model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$FRICTION$default_friction <- 38

#export 
model_exp <- toJSON(model, pretty = TRUE, auto_unbox = TRUE)
write(model_exp, "model_new.json")




#read in simulation json
simulation <- fromJSON(simulation_json)

#modify it
simulation$SIMULATION$TIME$end <- 3600

#export 
simulation_exp <- toJSON(simulation, pretty = TRUE, auto_unbox = TRUE)
write(simulation_exp, "simulation_new.json")





#RUN BAsement from RStudio
#setup
bas_setup(model_json, setup_h5)
#simulation
bas_simul(simulation_json, setup_h5, results_h5)
#export results
bas_results(results_json, results_h5, results_xdmf)


```


```{r}
#paths------
#INPUT
#model json path
model_json <- "hdm_models/GL1/model.json"
#simulation json path
simulation_json <- "hdm_models/GL1/simulation.json"
results_json <- "hdm_models/GL1/results.json"
#OUTPUT
setup_h5 <- "hdm_models/GL1/setup.h5"
results_h5 <- "hdm_models/GL1/results_31_76.h5"
#this can actually remain always the same
results_xdmf <- "hdm_models/GL1/results_31_76"

#read in model json
model <- fromJSON(model_json)

#modify it
#change mesh
mesh_path <- "U:/MZB/03_modelle/7_glenner/GL2/3_basement/Gl2_computational-mesh_gcp2_mod.2dm"
model$SETUP$DOMAIN$BASEPLANE_2D$GEOMETRY$mesh_file <- mesh_path

#change discharge
model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$BOUNDARY$STANDARD$discharge[1] <- 31.76

#change Strickler
model$SETUP$DOMAIN$BASEPLANE_2D$HYDRAULICS$FRICTION$default_friction <- 38

#export 
model_exp <- toJSON(model, pretty = TRUE, auto_unbox = TRUE)
write(model_exp, "model_new.json")




#read in simulation json
simulation <- fromJSON(simulation_json)

#modify it
simulation$SIMULATION$TIME$end <- 3600

#export 
simulation_exp <- toJSON(simulation, pretty = TRUE, auto_unbox = TRUE)
write(simulation_exp, "simulation_new.json")





#RUN BAsement from RStudio
#setup
bas_setup(model_json, setup_h5)
#simulation
bas_simul(simulation_json, setup_h5, results_h5)
#export results
bas_results(results_json, results_h5, results_xdmf)




```

