---
title: "Habitat_Model_VZH"
format: html
---

# Load packages 
```{r}
#clear R environment
rm(list = ls())

# check for a package, install and load 
pkgCheck <- function(x){ 
  if (!require(x,character.only = TRUE)){
    install.packages(x,dependencies=TRUE)
    if(!require(x,character.only = TRUE)) {
      stop()
    }
  }
}

pkgCheck("raster")
pkgCheck("spsurvey")
pkgCheck("terra")
pkgCheck("raster")
pkgCheck("ggplot2")
pkgCheck("tibble")
pkgCheck("readr")
pkgCheck("dplyr")
pkgCheck("tidyr")
pkgCheck("scales")

# load self-written functions 
source("mth_functions.R")
```

# Glenner
## GL1
```{r}
GL1_2_56_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_2_56_ezg.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_2_56_ezg.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_2_56_ezg.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_2_56_ezg.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_2_56_ezg.tif", 
                    river = "GL1", 
                    discharge = 2.56)
```

## GL2 
```{r}
GL2_2_37_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_2_37_ezg.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_2_37_ezg.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_2_37_ezg.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_2_37_ezg.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_2_37_ezg.tif", 
                    river = "GL2", 
                    discharge = 2.37)
```

# Landquart
## L2
```{r}
L2_9_54_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_9_54_ezg.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_9_54_ezg.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_9_54_ezg.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_9_54_ezg.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_9_54_ezg.tif", 
                   river = "L2", 
                   discharge = 9.54)
```

# Moesa
## M1
```{r}
M1_1_50_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_1_50_ezg.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_1_50_ezg.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_1_50_ezg.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_1_50_ezg.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_1_50_ezg.tif", 
                   river = "M1", 
                   discharge = 1.50)
```

# Sitter
## S1
```{r}
S1_1_94_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_1_94_ezg.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_1_94_ezg.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_1_94_ezg.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_1_94_ezg.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_1_94_ezg.tif", 
                   river = "S1", 
                   discharge = 1.94)
```

## S2
```{r}
S2_1_93_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_1_93_ezg.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_1_93_ezg.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_1_93_ezg.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_1_93_ezg.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_1_93_ezg.tif", 
                   river = "S2", 
                   discharge = 1.93)
```

# Thur
## TH4
```{r}
TH4_35_12_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_35_12_ezg.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_35_12_ezg.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_35_12_ezg.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_35_12_ezg.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_35_12_ezg.tif", 
                   river = "TH4", 
                   discharge = 35.12)
```

# Vorderrhein
## VR3
```{r}
VR3_21_51_ezg <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_21_51_ezg.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_21_51_ezg.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_21_51_ezg.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_21_51_ezg.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_21_51_ezg.tif", 
                   river = "VR3", 
                   discharge = 21.51)
```

# Bind Metric Results 
```{r}
# metrics
metric_results <- rbind(GL1_2_56_ezg$metrics, 
                        GL2_2_37_ezg$metrics, 
                        L2_9_54_ezg$metrics, 
                        M1_1_50_ezg$metrics,
                        S1_1_94_ezg$metrics, 
                        S2_1_93_ezg$metrics, 
                        TH4_35_12_ezg$metrics,
                        VR3_21_51_ezg$metrics)

# safe df into .csv file
write.csv(metric_results, file = "HSC_model/results_foen/results_foen_metrics_ezg.csv", row.names = FALSE)


# freq_tables
freq_tables <- rbind(GL1_2_56_ezg$freq, 
                     GL2_2_37_ezg$freq, 
                     L2_9_54_ezg$freq, 
                     M1_1_50_ezg$freq, 
                     S1_1_94_ezg$freq, 
                     S2_1_93_ezg$freq,
                     TH4_35_12_ezg$freq, 
                     VR3_21_51_ezg$freq)

# write data frame into .csv file
write.csv(freq_tables, file = "HSC_model/results_foen/results_foen_freq_tables_ezg.csv", row.names = FALSE)
```
 
                  
# Extract Modelled Values 
## Load Data
```{r}
# read .csv with lab results from river sections 
univariate <- read_delim("Pre_Processing/abiotic_mi_sampling/lab_ml_wd_v.csv")

# create clean df which only contains the values needed 
 univariate <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL1" | 
           Reach_Untersuchungsstelle == "GL2" |
           Reach_Untersuchungsstelle == "L2" |
           Reach_Untersuchungsstelle == "M1" |
           Reach_Untersuchungsstelle == "S1" |
           Reach_Untersuchungsstelle == "S2" |
           Reach_Untersuchungsstelle == "TH4" |
           Reach_Untersuchungsstelle == "VR3") |>
   dplyr::select(Reach_Untersuchungsstelle, x, y, abundance, shannon, k_index, rel_abundance) |>
   mutate(x = as.numeric(x),
          y = as.numeric(y))
```

## Extract 
```{r}
# read all raster results (one time flow velocity classes and one time for habitat suitability)
# NOTE: CHANGE TO RASTERS WHICH REPRESENT DISCHARGE AT SAMPLING DAY
GL1_class_ezg <- raster("HSC_model/results_foen/GL1_foen_class_2_56_ezg.tif")
GL1_HS_ezg <- raster("HSC_model/results_foen/GL1_foen_2_56_ezg.tif")
stack_GL1_ezg <- stack(GL1_class_ezg, GL1_HS_ezg)

GL2_class <- raster("HSC_model/results_foen/GL2_foen_class_2_37_ezg.tif")
GL2_HS <- raster("HSC_model/results_foen/GL2_foen_2_37_ezg.tif")
stack_GL2 <- stack(GL2_class, GL2_HS)

L2_class <- raster("HSC_model/results_foen/L2_foen_class_9_54_ezg.tif")
L2_HS <- raster("HSC_model/results_foen/L2_foen_9_54_ezg.tif")
stack_L2 <- stack(L2_class, L2_HS)

M1_class <- raster("HSC_model/results_foen/M1_foen_class_1_50_ezg.tif")
M1_HS <- raster("HSC_model/results_foen/M1_foen_1_50_ezg.tif")
stack_M1 <- stack(M1_class, M1_HS)

S1_class <- raster("HSC_model/results_foen/S1_foen_class_1_94_ezg.tif")
S1_HS <- raster("HSC_model/results_foen/S1_foen_1_94_ezg.tif")
stack_S1 <- stack(S1_class, S1_HS)

S2_class <- raster("HSC_model/results_foen/S2_foen_class_1_93_ezg.tif")
S2_HS <- raster("HSC_model/results_foen/S2_foen_1_93_ezg.tif")
stack_S2 <- stack(S2_class, S2_HS)

TH4_class <- raster("HSC_model/results_foen/TH4_foen_class_35_12_ezg.tif")
TH4_HS <- raster("HSC_model/results_foen/TH4_foen_35_12_ezg.tif")
stack_TH4 <- stack(TH4_class, TH4_HS)

VR3_class <- raster("HSC_model/results_foen/VR3_foen_class_21_51_ezg.tif")
VR3_HS <- raster("HSC_model/results_foen/VR3_foen_21_51_ezg.tif")
stack_VR3 <- stack(VR3_class, VR3_HS)

# prep extraction data 
## GL1
univariate_coord_GL1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL1") |>
  dplyr::select(x, y) 

univariate_GL1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL1") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance) 

## GL2
univariate_coord_GL2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL2") |>
  dplyr::select(x, y) 

univariate_GL2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL2") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance)

## L2
univariate_coord_L2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "L2") |>
  dplyr::select(x, y) 

univariate_L2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "L2") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance)

## M1
univariate_coord_M1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "M1") |>
  dplyr::select(x, y) 

univariate_M1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "M1") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance)

## S1
univariate_coord_S1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S1") |>
  dplyr::select(x, y) 

univariate_S1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S1") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance)

## S2
univariate_coord_S2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S2") |>
  dplyr::select(x, y) 

univariate_S2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S2") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance)

## TH4
univariate_coord_TH4 <- univariate |>
  subset(Reach_Untersuchungsstelle == "TH4") |>
  dplyr::select(x, y) 

univariate_TH4 <- univariate |>
  subset(Reach_Untersuchungsstelle == "TH4") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance)

## VR3
univariate_coord_VR3 <- univariate |>
  subset(Reach_Untersuchungsstelle == "VR3") |>
  dplyr::select(x, y) 

univariate_VR3 <- univariate |>
  subset(Reach_Untersuchungsstelle == "VR3") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, rel_abundance, abundance, shannon, k_index, rel_abundance)
  

# extract raster information for regression analysis later
regr_data_GL1 <- raster::extract(stack_GL1_ezg, univariate_coord_GL1)
data_GL1 <- cbind(regr_data_GL1, univariate_GL1) |>
  dplyr::rename(foen_class = GL1_foen_class_2_56_ezg,
         foen_hsi = GL1_foen_2_56_ezg)

regr_data_GL2 <- raster::extract(stack_GL2, univariate_coord_GL2)
data_GL2 <- cbind(regr_data_GL2, univariate_GL2) |>
  dplyr::rename(foen_class = GL2_foen_class_2_37_ezg,
         foen_hsi = GL2_foen_2_37_ezg)

regr_data_L2 <- raster::extract(stack_L2, univariate_coord_L2)
data_L2 <- cbind(regr_data_L2, univariate_L2) |>
  dplyr::rename(foen_class = L2_foen_class_9_54_ezg,
         foen_hsi = L2_foen_9_54_ezg)

regr_data_M1 <- raster::extract(stack_M1, univariate_coord_M1)
data_M1 <- cbind(regr_data_M1, univariate_M1) |>
  dplyr::rename(foen_class = M1_foen_class_1_50_ezg,
         foen_hsi = M1_foen_1_50_ezg)

regr_data_S1 <- raster::extract(stack_S1, univariate_coord_S1)
data_S1 <- cbind(regr_data_S1, univariate_S1) |>
  dplyr::rename(foen_class = S1_foen_class_1_94_ezg,
         foen_hsi = S1_foen_1_94_ezg)

regr_data_S2 <- raster::extract(stack_S2, univariate_coord_S2)
data_S2 <- cbind(regr_data_S2, univariate_S2) |>
  dplyr::rename(foen_class = S2_foen_class_1_93_ezg,
         foen_hsi = S2_foen_1_93_ezg)

regr_data_TH4 <- raster::extract(stack_TH4, univariate_coord_TH4)
data_TH4 <- cbind(regr_data_TH4, univariate_TH4) |>
  dplyr::rename(foen_class = TH4_foen_class_35_12_ezg,
         foen_hsi = TH4_foen_35_12_ezg)

regr_data_VR3 <- raster::extract(stack_VR3, univariate_coord_VR3)
data_VR3 <- cbind(regr_data_VR3, univariate_VR3) |>
  dplyr::rename(foen_class = VR3_foen_class_21_51_ezg,
         foen_hsi = VR3_foen_21_51_ezg)

# bind results together 
results <- rbind(data_GL1, data_GL2, data_L2, data_M1, data_S1, data_S2, data_TH4, data_VR3)

# export results to .csv dataframe
write.csv(results, "Stat_Analysis/hsc_regr_analysis.csv", row.names = FALSE)
```
