---
title: "Habitat_Model_VZH"
format: html
---

# Load packages 
```{r}
#clear R environment
rm(list = ls())

# check for a package, install and load 
pkgCheck <- function(x){ 
  if (!require(x,character.only = TRUE)){
    install.packages(x,dependencies=TRUE)
    if(!require(x,character.only = TRUE)) {
      stop()
    }
  }
}

pkgCheck("raster")
pkgCheck("spsurvey")
pkgCheck("terra")
pkgCheck("raster")
pkgCheck("ggplot2")
pkgCheck("tibble")
pkgCheck("readr")
pkgCheck("dplyr")
pkgCheck("tidyr")
pkgCheck("scales")

# load self-written functions 
source("mth_functions.R")
```

# Glenner
## GL1
```{r}
GL1_3_28 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_3_28.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_3_28.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_3_28.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_3_28.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_3_28.tif", 
                    river = "GL1", 
                    discharge = 3.28)

GL1_6_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_6_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_6_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_6_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_6_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_6_00.tif", 
                    river = "GL1", 
                    discharge = 6.00)

GL1_9_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_9_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_9_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_9_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_9_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_9_00.tif", 
                    river = "GL1", 
                    discharge = 9.00)

GL1_12_68 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_12_68.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_12_68.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_12_68.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_12_68.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_12_68.tif", 
                    river = "GL1", 
                    discharge = 12.68)

GL1_16_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_16_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_16_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_16_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_16_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_16_00.tif", 
                    river = "GL1", 
                    discharge = 16.00)

GL1_19_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_19_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_19_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_19_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_19_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_19_00.tif", 
                    river = "GL1", 
                    discharge = 19.00)

GL1_22_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_22_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_22_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_22_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_22_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_22_00.tif", 
                    river = "GL1", 
                    discharge = 22.00)

GL1_25_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_25_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_25_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_25_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_25_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_25_00.tif", 
                    river = "GL1", 
                    discharge = 25.00)

GL1_28_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_28_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_28_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_28_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_28_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_28_00.tif", 
                    river = "GL1", 
                    discharge = 28.00)

GL1_31_76 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL1_v_31_76.tif", 
                    base_flow = "Pre_Processing/raster_files/GL1_v_3_28.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL1_foen_class_pers_31_76.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL1_foen_class_31_76.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL1_foen_31_76.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL1_foen_pers_31_76.tif", 
                    river = "GL1", 
                    discharge = 31.76)
```

## GL2 
```{r}
GL2_3_21 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_3_21.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_3_21.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_3_21.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_3_21.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_3_21.tif", 
                    river = "GL2", 
                    discharge = 3.21)

GL2_6_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_6_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_6_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_6_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_6_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_6_00.tif", 
                    river = "GL2", 
                    discharge = 6.00)

GL2_9_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_9_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_9_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_9_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_9_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_9_00.tif", 
                    river = "GL2", 
                    discharge = 9.00)

GL2_11_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_11_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_11_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_11_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_11_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_11_00.tif", 
                    river = "GL2", 
                    discharge = 11.00)

GL2_12_52 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_12_52.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_12_52.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_12_52.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_12_52.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_12_52.tif", 
                    river = "GL2", 
                    discharge = 12.52)

GL2_16_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_16_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_16_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_16_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_16_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_16_00.tif", 
                    river = "GL2", 
                    discharge = 16.00)

GL2_19_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_19_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_19_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_19_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_19_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_19_00.tif", 
                    river = "GL2", 
                    discharge = 19.00)

GL2_22_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_22_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_22_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_22_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_22_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_22_00.tif", 
                    river = "GL2", 
                    discharge = 22.00)

GL2_25_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_25_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_25_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_25_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_25_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_25_00.tif", 
                    river = "GL2", 
                    discharge = 25.00)


GL2_28_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_28_00.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_28_00.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_28_00.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_28_00.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_28_00.tif", 
                    river = "GL2", 
                    discharge = 28.00)

GL2_31_53 <- foen_hm(raster_path = "Pre_Processing/raster_files/GL2_v_31_53.tif", 
                    base_flow = "Pre_Processing/raster_files/GL2_v_3_21.tif",
                    output_path_pers_reclass =
                      "HSC_model/results_foen/GL2_foen_class_pers_31_53.tif", 
                    output_path_reclass =
                      "HSC_model/results_foen/GL2_foen_class_31_53.tif", 
                    HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                    col1 = "Bewohnbarkeitsklasse",
                    col2 = "HSI",
                    output_path_hm = "HSC_model/results_foen/GL2_foen_31_53.tif",
                    output_path_hm_persistent =
                      "HSC_model/results_foen/GL2_foen_pers_31_53.tif", 
                    river = "GL2", 
                    discharge = 31.53)
```

# Landquart
## L2
```{r}
L2_2_40 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_2_40.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_2_40.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_2_40.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_2_40.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_2_40.tif", 
                   river = "L2", 
                   discharge = 2.40)

L2_3_90 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_3_90.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_3_90.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_3_90.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_3_90.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_3_90.tif", 
                   river = "L2", 
                   discharge = 3.90)

L2_7_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_7_00.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_7_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_7_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_7_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_7_00.tif", 
                   river = "L2", 
                   discharge = 7.00)

L2_9_24 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_9_24.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_9_24.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_9_24.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_9_24.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_9_24.tif", 
                   river = "L2", 
                   discharge = 9.24)

L2_11_40 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_11_40.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_11_40.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_11_40.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_11_40.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_11_40.tif", 
                   river = "L2", 
                   discharge = 11.40)

L2_13_30 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_13_30.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_13_30.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_13_30.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_13_30.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_13_30.tif", 
                   river = "L2", 
                   discharge = 13.30)

L2_16_50 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_16_50.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_16_50.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_16_50.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_16_50.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_16_50.tif", 
                   river = "L2", 
                   discharge = 16.50)

L2_18_90 <- foen_hm(raster_path = "Pre_Processing/raster_files/L2_v_18_90.tif", 
                   base_flow = "Pre_Processing/raster_files/L2_v_2_40.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/L2_foen_class_pers_18_90.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/L2_foen_class_18_90.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/L2_foen_18_90.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/L2_foen_pers_18_90.tif", 
                   river = "L2", 
                   discharge = 18.90)
```


# Moesa
## M1
```{r}
M1_0_47 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_0_47.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_0_47.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_0_47.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_0_47.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_0_47.tif", 
                   river = "M1", 
                   discharge = 0.47)

M1_0_60 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_0_60.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_0_60.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_0_60.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_0_60.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_0_60.tif", 
                   river = "M1", 
                   discharge = 0.60)

M1_4_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_4_00.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_4_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_4_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_4_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_4_00.tif", 
                   river = "M1", 
                   discharge = 4.00)

M1_6_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_6_00.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_6_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_6_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_6_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_6_00.tif", 
                   river = "M1", 
                   discharge = 6.00)

M1_8_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_8_00.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_8_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_8_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_8_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_8_00.tif", 
                   river = "M1", 
                   discharge = 8.00)

M1_10_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_10_00.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_10_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_10_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_10_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_10_00.tif", 
                   river = "M1", 
                   discharge = 10.00)

M1_12_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_12_00.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_12_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_12_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_12_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_12_00.tif", 
                   river = "M1", 
                   discharge = 12.00)

M1_14_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_14_00.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_14_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_14_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_14_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_14_00.tif", 
                   river = "M1", 
                   discharge = 14.00)

M1_16_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_16_00.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_16_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_16_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_16_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_16_00.tif", 
                   river = "M1", 
                   discharge = 16.00)

M1_18_84 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_18_84.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_18_84.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_18_84.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_18_84.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_18_84.tif", 
                   river = "M1", 
                   discharge = 18.84)

M1_22_84 <- foen_hm(raster_path = "Pre_Processing/raster_files/M1_v_22_84.tif", 
                   base_flow = "Pre_Processing/raster_files/M1_v_0_47.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/M1_foen_class_pers_22_84.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/M1_foen_class_22_84.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/M1_foen_22_84.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/M1_foen_pers_22_84.tif", 
                   river = "M1", 
                   discharge = 22.84)
```

# Sitter
## S1
```{r}
S1_2_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_2_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_2_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_2_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_2_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_2_00.tif", 
                   river = "S1", 
                   discharge = 2.00)

S1_3_70 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_3_70.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_3_70.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_3_70.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_3_70.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_3_70.tif", 
                   river = "S1", 
                   discharge = 3.70)

S1_6_50 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_6_50.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_6_50.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_6_50.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_6_50.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_6_50.tif", 
                   river = "S1", 
                   discharge = 6.50)

S1_8_50 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_8_50.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_8_50.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_8_50.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_8_50.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_8_50.tif", 
                   river = "S1", 
                   discharge = 8.50)

S1_10_68 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_10_68.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_10_68.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_10_68.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_10_68.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_10_68.tif", 
                   river = "S1", 
                   discharge = 10.68)

S1_13_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_13_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_13_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_13_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_13_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_13_00.tif", 
                   river = "S1", 
                   discharge = 13.00)

S1_15_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_15_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_15_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_15_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_15_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_15_00.tif", 
                   river = "S1", 
                   discharge = 15.00)

S1_18_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_18_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_18_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_18_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_18_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_18_00.tif", 
                   river = "S1", 
                   discharge = 18.00)

S1_20_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S1_v_20_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S1_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S1_foen_class_pers_20_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S1_foen_class_20_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S1_foen_20_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S1_foen_pers_20_00.tif", 
                   river = "S1", 
                   discharge = 20.00)
```

## S2
```{r}
S2_2_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_2_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_2_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_2_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_2_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_2_00.tif", 
                   river = "S2", 
                   discharge = 2.00)

S2_3_20 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_3_20.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_3_20.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_3_20.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_3_20.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_3_20.tif", 
                   river = "S2", 
                   discharge = 3.20)

S2_6_50 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_6_50.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_6_50.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_6_50.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_6_50.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_6_50.tif", 
                   river = "S2", 
                   discharge = 6.50)

S2_8_50 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_8_50.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_8_50.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_8_50.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_8_50.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_8_50.tif", 
                   river = "S2", 
                   discharge = 8.50)

S2_10_93 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_10_93.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_10_93.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_10_93.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_10_93.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_10_93.tif", 
                   river = "S2", 
                   discharge = 10.93)

S2_13_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_13_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_13_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_13_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_13_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_13_00.tif", 
                   river = "S2", 
                   discharge = 13.00)

S2_15_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_15_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_15_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_15_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_15_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_15_00.tif", 
                   river = "S2", 
                   discharge = 15.00)

S2_18_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_18_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_18_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_18_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_18_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_18_00.tif", 
                   river = "S2", 
                   discharge = 18.00)

S2_20_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/S2_v_20_00.tif", 
                   base_flow = "Pre_Processing/raster_files/S2_v_2_00.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/S2_foen_class_pers_20_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/S2_foen_class_20_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/S2_foen_20_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/S2_foen_pers_20_00.tif", 
                   river = "S2", 
                   discharge = 20.00)
```

# Thur
## TH4
```{r}
TH4_11_45 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_11_45.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_11_45.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_11_45.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_11_45.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_11_45.tif", 
                   river = "TH4", 
                   discharge = 11.45)

TH4_15_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_15_00.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_15_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_15_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_15_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_15_00.tif", 
                   river = "TH4", 
                   discharge = 15.00)

TH4_18_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_18_00.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_18_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_18_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_18_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_18_00.tif", 
                   river = "TH4", 
                   discharge = 18.00)

TH4_19_96 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_19_96.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_19_96.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_19_96.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_19_96.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_19_96.tif", 
                   river = "TH4", 
                   discharge = 19.96)

TH4_22_50 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_22_50.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_22_50.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_22_50.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_22_50.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_22_50.tif", 
                   river = "TH4", 
                   discharge = 22.50)
 
TH4_25_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_25_00.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_25_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_25_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_25_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_25_00.tif", 
                   river = "TH4", 
                   discharge = 25.00)

TH4_27_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_27_00.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_27_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_27_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_27_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_27_00.tif", 
                   river = "TH4", 
                   discharge = 27.00)

TH4_30_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_30_00.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_30_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_30_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_30_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_30_00.tif", 
                   river = "TH4", 
                   discharge = 30.00)

TH4_32_93 <- foen_hm(raster_path = "Pre_Processing/raster_files/TH4_v_32_93.tif", 
                   base_flow = "Pre_Processing/raster_files/TH4_v_11_45.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/TH4_foen_class_pers_32_93.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/TH4_foen_class_32_93.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/TH4_foen_32_93.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/TH4_foen_pers_32_93.tif", 
                   river = "TH4", 
                   discharge = 32.93)
```

# Vorderrhein
## VR3
```{r}
VR3_2_90 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_2_90.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_2_90.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_2_90.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_2_90.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_2_90.tif", 
                   river = "VR3", 
                   discharge = 2.90)

VR3_6_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_6_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_6_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_6_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_6_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_6_00.tif", 
                   river = "VR3", 
                   discharge = 6.00)

VR3_9_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_9_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_9_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_9_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_9_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_9_00.tif", 
                   river = "VR3", 
                   discharge = 9.00)

VR3_12_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_12_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_12_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_12_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_12_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_12_00.tif", 
                   river = "VR3", 
                   discharge = 12.00)

VR3_15_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_15_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_15_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_15_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_15_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_15_00.tif", 
                   river = "VR3", 
                   discharge = 15.00)

VR3_18_80 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_18_80.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_18_80.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_18_80.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_18_80.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_18_80.tif", 
                   river = "VR3", 
                   discharge = 18.80)

VR3_22_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_22_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_22_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_22_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_22_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_22_00.tif", 
                   river = "VR3", 
                   discharge = 22.00)

VR3_25_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_25_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_25_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_25_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_25_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_25_00.tif", 
                   river = "VR3", 
                   discharge = 25.00)

VR3_28_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_28_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_28_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_28_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_28_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_28_00.tif", 
                   river = "VR3", 
                   discharge = 28.00)

VR3_31_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_31_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_31_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_31_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_31_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_31_00.tif", 
                   river = "VR3", 
                   discharge = 31.00)

VR3_34_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_34_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_34_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_34_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_34_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_34_00.tif", 
                   river = "VR3", 
                   discharge = 34.00)

VR3_37_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_37_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_37_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_37_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_37_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_37_00.tif", 
                   river = "VR3", 
                   discharge = 37.00)

VR3_40_10 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_40_10.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_40_10.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_40_10.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_40_10.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_40_10.tif", 
                   river = "VR3", 
                   discharge = 40.10)

VR3_43_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_43_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_43_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_43_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_43_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_43_00.tif", 
                   river = "VR3", 
                   discharge = 43.00)

VR3_46_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_46_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_46_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_46_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_46_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_46_00.tif", 
                   river = "VR3", 
                   discharge = 46.00)

VR3_48_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_48_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_48_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_48_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_48_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_48_00.tif", 
                   river = "VR3", 
                   discharge = 48.00)

VR3_50_00 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_50_00.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_50_00.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_50_00.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_50_00.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_50_00.tif", 
                   river = "VR3", 
                   discharge = 50.00)

VR3_52_90 <- foen_hm(raster_path = "Pre_Processing/raster_files/VR3_v_52_90.tif", 
                   base_flow = "Pre_Processing/raster_files/VR3_v_2_90.tif",
                   output_path_pers_reclass =
                     "HSC_model/results_foen/VR3_foen_class_pers_52_90.tif", 
                   output_path_reclass =
                     "HSC_model/results_foen/VR3_foen_class_52_90.tif", 
                   HSC_path = "HSC_model/HSC_MI/HSC_MI.csv", 
                   col1 = "Bewohnbarkeitsklasse",
                   col2 = "HSI",
                   output_path_hm = "HSC_model/results_foen/VR3_foen_52_90.tif",
                   output_path_hm_persistent =
                     "HSC_model/results_foen/VR3_foen_pers_52_90.tif", 
                   river = "VR3", 
                   discharge = 52.90)
```

# Bind Metric Results 
```{r}
# GL1 - ok
# GL2 - ok
# L2 - ok
# M1 - ok
# S1 - ok
# S2 - ok 
# TH4 - ok
# VR3 - ok

# metrics
metric_results <- rbind(GL1_3_28$metrics, GL1_6_00$metrics, GL1_9_00$metrics, GL1_12_68$metrics, GL1_16_00$metrics,
                        GL1_19_00$metrics, GL1_22_00$metrics, GL1_25_00$metrics, GL1_28_00$metrics, GL1_31_76$metrics,
                        
                        GL2_3_21$metrics, GL2_6_00$metrics, GL2_9_00$metrics, GL2_11_00$metrics, GL2_12_52$metrics,
                        GL2_16_00$metrics, GL2_19_00$metrics, GL2_22_00$metrics, GL2_25_00$metrics, GL2_28_00$metrics,
                        GL2_31_53$metrics,
                        
                        L2_2_40$metrics, L2_3_90$metrics, L2_7_00$metrics, L2_9_24$metrics, L2_11_40$metrics, L2_13_30$metrics,
                        L2_16_50$metrics, L2_18_90$metrics,
                        
                        M1_0_47$metrics, M1_0_60$metrics, M1_4_00$metrics, M1_6_00$metrics, M1_8_00$metrics, M1_10_00$metrics,
                        M1_12_00$metrics, M1_14_00$metrics, M1_16_00$metrics, M1_18_84$metrics, M1_22_84$metrics,
                        
                        S1_2_00$metrics, S1_3_70$metrics, S1_6_50$metrics, S1_8_50$metrics, S1_10_68$metrics, S1_13_00$metrics,
                        S1_15_00$metrics, S1_18_00$metrics, S1_20_00$metrics,
                        
                        S2_2_00$metrics, S2_3_20$metrics, S2_6_50$metrics, S2_8_50$metrics, S2_10_93$metrics, S2_13_00$metrics,
                        S2_15_00$metrics, S2_18_00$metrics, S2_20_00$metrics,
                        
                        TH4_11_45$metrics, TH4_15_00$metrics, TH4_18_00$metrics, TH4_19_96$metrics, TH4_22_50$metrics,
                        TH4_25_00$metrics, TH4_27_00$metrics, TH4_30_00$metrics, TH4_32_93$metrics,
                        
                          VR3_2_90$metrics, VR3_6_00$metrics, VR3_9_00$metrics, VR3_12_00$metrics, VR3_15_00$metrics,
                        VR3_18_80$metrics, VR3_22_00$metrics, VR3_25_00$metrics, VR3_28_00$metrics, VR3_31_00$metrics,
                        VR3_34_00$metrics, VR3_37_00$metrics, VR3_40_10$metrics, VR3_43_00$metrics, VR3_46_00$metrics,
                        VR3_48_00$metrics, VR3_50_00$metrics, VR3_52_90$metrics)

# safe df into .csv file
write.csv(metric_results, file = "HSC_model/results_foen/results_foen_metrics.csv", row.names = FALSE)

# GL1 - ok
# GL2 - ok
# L2 - ok
# M1 - ok
# S1 - ok
# S2 - ok
# TH4 - ok
# VR3 - ok

# freq_tables
freq_tables <- rbind(GL1_3_28$freq, GL1_6_00$freq, GL1_9_00$freq, GL1_12_68$freq, GL1_16_00$freq,
                     GL1_19_00$freq, GL1_22_00$freq, GL1_25_00$freq, GL1_28_00$freq, GL1_31_76$freq,
                        
                     GL2_3_21$freq, GL2_6_00$freq, GL2_9_00$freq, GL2_11_00$freq, GL2_12_52$freq, GL2_16_00$freq,
                     GL2_19_00$freq, GL2_22_00$freq, GL2_25_00$freq, GL2_28_00$freq, GL2_31_53$freq,
                     
                     L2_2_40$freq, L2_3_90$freq, L2_7_00$freq, L2_9_24$freq, L2_11_40$freq, L2_13_30$freq, L2_16_50$freq,
                     L2_18_90$freq,
                     
                     M1_0_47$freq, M1_0_60$freq, M1_4_00$freq, M1_6_00$freq, M1_8_00$freq, M1_10_00$freq, M1_12_00$freq,
                     M1_14_00$freq, M1_16_00$freq, M1_18_84$freq, M1_22_84$freq,
                     
                     S1_2_00$freq, S1_3_70$freq, S1_6_50$freq, S1_8_50$freq, S1_10_68$freq, S1_13_00$freq, S1_15_00$freq,
                     S1_18_00$freq, S1_20_00$freq,
                     
                     S2_2_00$freq, S2_3_20$freq, S2_6_50$freq, S2_8_50$freq, S2_10_93$freq, S2_13_00$freq, S2_15_00$freq,
                     S2_18_00$freq, S2_20_00$freq,
                     
                     TH4_11_45$freq, TH4_15_00$freq, TH4_18_00$freq, TH4_19_96$freq, TH4_22_50$freq, TH4_25_00$freq,
                     TH4_27_00$freq, TH4_30_00$freq, TH4_32_93$freq,
                     
                     VR3_2_90$freq, VR3_6_00$freq, VR3_9_00$freq, VR3_12_00$freq, VR3_15_00$freq, VR3_18_80$freq, VR3_22_00$freq,
                     VR3_25_00$freq, VR3_28_00$freq, VR3_31_00$freq, VR3_34_00$freq, VR3_37_00$freq, VR3_40_10$freq,
                     VR3_43_00$freq, VR3_46_00$freq, VR3_48_00$freq, VR3_50_00$freq, VR3_52_90$freq)

# write data frame into .csv file
write.csv(freq_tables, file = "HSC_model/results_foen/results_foen_freq_tables.csv", row.names = FALSE)
```
 
                  
# Extract Modelled Values 
## Load Data
```{r}
# read .csv with lab results from river sections 
univariate <- read_delim("Pre_Processing/abiotic_mi_sampling/lab_univariate.csv")

# create clean df which only contains the values needed 
 univariate <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL1" | 
           Reach_Untersuchungsstelle == "GL2" |
           Reach_Untersuchungsstelle == "L2" |
           Reach_Untersuchungsstelle == "M1" |
           Reach_Untersuchungsstelle == "S1" |
           Reach_Untersuchungsstelle == "S2" |
           Reach_Untersuchungsstelle == "TH4" |
           Reach_Untersuchungsstelle == "VR3") |>
   dplyr::select(Reach_Untersuchungsstelle, x, y, abundance, shannon, k_index) |>
   mutate(x = as.numeric(x),
          y = as.numeric(y))
```

## Extract 
```{r}
# read all raster results (one time flow velocity classes and one time for habitat suitability)
# NOTE: CHANGE TO RASTERS WHICH REPRESENT DISCHARGE AT SAMPLING DAY
GL1_class <- raster("HSC_model/results_foen/GL1_foen_class_3_28.tif")
GL1_HS <- raster("HSC_model/results_foen/GL1_foen_3_28.tif")
stack_GL1 <- stack(GL1_class, GL1_HS)

GL2_class <- raster("HSC_model/results_foen/GL2_foen_class_3_21.tif")
GL2_HS <- raster("HSC_model/results_foen/GL2_foen_3_21.tif")
stack_GL2 <- stack(GL2_class, GL2_HS)

L2_class <- raster("HSC_model/results_foen/L2_foen_class_2_40.tif")
L2_HS <- raster("HSC_model/results_foen/L2_foen_2_40.tif")
stack_L2 <- stack(L2_class, L2_HS)

M1_class <- raster("HSC_model/results_foen/M1_foen_class_0_47.tif")
M1_HS <- raster("HSC_model/results_foen/M1_foen_0_47.tif")
stack_M1 <- stack(M1_class, M1_HS)

S1_class <- raster("HSC_model/results_foen/S1_foen_class_2_00.tif")
S1_HS <- raster("HSC_model/results_foen/S1_foen_2_00.tif")
stack_S1 <- stack(S1_class, S1_HS)

S2_class <- raster("HSC_model/results_foen/S2_foen_class_2_00.tif")
S2_HS <- raster("HSC_model/results_foen/S2_foen_2_00.tif")
stack_S2 <- stack(S2_class, S2_HS)

TH4_class <- raster("HSC_model/results_foen/TH4_foen_class_11_45.tif")
TH4_HS <- raster("HSC_model/results_foen/TH4_foen_11_45.tif")
stack_TH4 <- stack(TH4_class, TH4_HS)

VR3_class <- raster("HSC_model/results_foen/VR3_foen_class_2_90.tif")
VR3_HS <- raster("HSC_model/results_foen/VR3_foen_2_90.tif")
stack_VR3 <- stack(VR3_class, VR3_HS)

# prep extraction data 
## GL1
univariate_coord_GL1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL1") |>
  dplyr::select(x, y) 

univariate_GL1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL1") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index) 

## GL2
univariate_coord_GL2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL2") |>
  dplyr::select(x, y) 

univariate_GL2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "GL2") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index)

## L2
univariate_coord_L2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "L2") |>
  dplyr::select(x, y) 

univariate_L2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "L2") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index)

## M1
univariate_coord_M1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "M1") |>
  dplyr::select(x, y) 

univariate_M1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "M1") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index)

## S1
univariate_coord_S1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S1") |>
  dplyr::select(x, y) 

univariate_S1 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S1") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index)

## S2
univariate_coord_S2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S2") |>
  dplyr::select(x, y) 

univariate_S2 <- univariate |>
  subset(Reach_Untersuchungsstelle == "S2") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index)

## TH4
univariate_coord_TH4 <- univariate |>
  subset(Reach_Untersuchungsstelle == "TH4") |>
  dplyr::select(x, y) 

univariate_TH4 <- univariate |>
  subset(Reach_Untersuchungsstelle == "TH4") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index)

## VR3
univariate_coord_VR3 <- univariate |>
  subset(Reach_Untersuchungsstelle == "VR3") |>
  dplyr::select(x, y) 

univariate_VR3 <- univariate |>
  subset(Reach_Untersuchungsstelle == "VR3") |>
  dplyr::select(x, y, Reach_Untersuchungsstelle, abundance, shannon, k_index)
  

# extract raster information for regression analysis later
regr_data_GL1 <- extract(stack_GL1, univariate_coord_GL1)
data_GL1 <- cbind(regr_data_GL1, univariate_GL1) |>
  rename(foen_class = GL1_foen_class_3_28,
         foen_hsi = GL1_foen_3_28)

regr_data_GL2 <- extract(stack_GL2, univariate_coord_GL2)
data_GL2 <- cbind(regr_data_GL2, univariate_GL2) |>
  rename(foen_class = GL2_foen_class_3_21,
         foen_hsi = GL2_foen_3_21)

regr_data_L2 <- extract(stack_L2, univariate_coord_L2)
data_L2 <- cbind(regr_data_L2, univariate_L2) |>
  rename(foen_class = L2_foen_class_2_40,
         foen_hsi = L2_foen_2_40)

regr_data_M1 <- extract(stack_M1, univariate_coord_M1)
data_M1 <- cbind(regr_data_M1, univariate_M1) |>
  rename(foen_class = M1_foen_class_0_47,
         foen_hsi = M1_foen_0_47)

regr_data_S1 <- extract(stack_S1, univariate_coord_S1)
data_S1 <- cbind(regr_data_S1, univariate_S1) |>
  rename(foen_class = S1_foen_class_2_00,
         foen_hsi = S1_foen_2_00)

regr_data_S2 <- extract(stack_S2, univariate_coord_S2)
data_S2 <- cbind(regr_data_S2, univariate_S2) |>
  rename(foen_class = S2_foen_class_2_00,
         foen_hsi = S2_foen_2_00)

regr_data_TH4 <- extract(stack_TH4, univariate_coord_TH4)
data_TH4 <- cbind(regr_data_TH4, univariate_TH4) |>
  rename(foen_class = TH4_foen_class_11_45,
         foen_hsi = TH4_foen_11_45)

regr_data_VR3 <- extract(stack_VR3, univariate_coord_VR3)
data_VR3 <- cbind(regr_data_VR3, univariate_VR3) |>
  rename(foen_class = VR3_foen_class_2_90,
         foen_hsi = VR3_foen_2_90)

# bind results together 
results <- rbind(data_GL1, data_GL2, data_L2, data_M1, data_S1, data_S2, data_TH4, data_VR3)

# export results to .csv dataframe
write.csv(results, "Stat_Analysis/hsc_regr_analysis.csv", row.names = FALSE)
```
