---
title: "basement_simulations"
format: html
---

# Load packages
```{r}
# clear memory 
rm(list = ls())

# load all Packages
pkgCheck <- function(x){ 
  if (!require(x,character.only = TRUE)){
    install.packages(x,dependencies=TRUE)
    if(!require(x,character.only = TRUE)) {
      stop()
    }
  }
}

pkgCheck("hdf5r")
pkgCheck("sp")
pkgCheck("sf")
pkgCheck("ggplot2")
pkgCheck("dplyr")
pkgCheck("readr")
pkgCheck("Metrics")
pkgCheck("raster")
pkgCheck("rgeos")
pkgCheck("hydroGOF")
pkgCheck("jsonlite")

# Load self-written functions
source("mth_functions.R")

# set working directory for model simulations
setwd("Pre_Processing")
```


# Glenner
## GL1
```{r}
GL1_2_74 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_2_74.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_2_74",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 2.74,
                       strickler = 38)

GL1_3_28 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_3_28.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_3_28",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 3.28,
                       strickler = 38)

GL1_6_00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_6_00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_6_00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 6.00, 
                       strickler = 38)

GL1_9_00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_9_00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_9_00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 9.00, 
                       strickler = 38)

GL1_12_68 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_12_68.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_12_68",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 12.68, 
                       strickler = 38)

GL1_16_00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_16_00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_16_00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 16.00, 
                       strickler = 38)

GL1_19_00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_19_00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_19_00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 19.00, 
                       strickler = 38)

GL1_22_00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_22_00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_22_00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 22.00, 
                       strickler = 38)

GL1_25_00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_25_00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_25_00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 25.00, 
                       strickler = 38)

GL1_28_00 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_28_00.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_28_00",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 28.00, 
                       strickler = 38)

GL1_31_76 <- basement(model_json = "hdm_models/GL1/model.json",
                       model_new = "hdm_models/GL1/model_new.json",
                       mesh_path = "hdm_models/GL1/GL1_mesh_computational-mesh_3.2dm", 
                       simulation_json = "hdm_models/GL1/simulation.json",
                       simulation_new = "hdm_models/GL1/simulation_new.json",
                       setup_h5 = "hdm_models/GL1/setup.h5",
                       results_h5 = "hdm_models/GL1/results_GL1_31_76.h5",
                       results_xdmf = "hdm_models/GL1/results_GL1_31_76",
                       results_json = "hdm_models/GL1/results.json",
                       discharge = 31.76, 
                       strickler = 38)
```



## GL2
```{r}
GL2_3_21 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_3_21.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_3_21",
             results_json = "hdm_models/GL2/results.json",
             discharge = 3.21, 
             strickler = 38)

GL2_6_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_6_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_6_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 6.00, 
             strickler = 38)

GL2_9_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_9_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_9_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 9.00, 
             strickler = 38)

GL2_11_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_11_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_11_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 11.00, 
             strickler = 38)

GL2_12_52 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_12_52.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_12_52",
             results_json = "hdm_models/GL2/results.json",
             discharge = 12.52, 
             strickler = 38)

GL2_16_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_16_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_16_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 16.00, 
             strickler = 38)

GL2_19_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_19_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_19_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 19.00, 
             strickler = 38)

GL2_22_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_22_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_22_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 22.00, 
             strickler = 38)

GL2_25_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_25_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_25_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 25.00, 
             strickler = 38)

GL2_28_00 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_28_00.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_28_00",
             results_json = "hdm_models/GL2/results.json",
             discharge = 28.00, 
             strickler = 38)

GL2_31_53 <-  basement(model_json = "hdm_models/GL2/model.json", 
             model_new = "hdm_models/GL2/model_new.json",
             mesh_path = "hdm_models/GL2/Gl2_computational-mesh_mod.2dm", 
             simulation_json = "hdm_models/GL2/simulation.json",
             simulation_new = "hdm_models/GL2/simulation_new.json",
             setup_h5 = "hdm_models/GL2/setup.h5",
             results_h5 = "hdm_models/GL2/results_GL2_31_53.h5",
             results_xdmf = "hdm_models/GL2/results_GL2_31_53",
             results_json = "hdm_models/GL2/results.json",
             discharge = 31.53,
             strickler = 38)
```

          
# Landquart
## L2 
```{r}
L2_2_40 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_2_40.h5",
                     results_xdmf = "hdm_models/L2/results_L2_2_40",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 2.40,
                     strickler = 11.5)

L2_3_90 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_3_90.h5",
                     results_xdmf = "hdm_models/L2/results_L2_3_90",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 3.90,
                     strickler = 11.5)

L2_7_00 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_7_00.h5",
                     results_xdmf = "hdm_models/L2/results_L2_7_00",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 7.00,
                     strickler = 11.5)

L2_7_95 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_7_95.h5",
                     results_xdmf = "hdm_models/L2/results_L2_7_95",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 7.95,
                     strickler = 11.5)

L2_9_24 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_9_24.h5",
                     results_xdmf = "hdm_models/L2/results_L2_9_24",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 9.24,
                     strickler = 11.5)

L2_11_40 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_11_40.h5",
                     results_xdmf = "hdm_models/L2/results_L2_11_40",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 11.40,
                     strickler = 11.5)


L2_13_30 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_13_30.h5",
                     results_xdmf = "hdm_models/L2/results_L2_13_30",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 13.30,
                     strickler = 11.5)

L2_16_50 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_16_50.h5",
                     results_xdmf = "hdm_models/L2/results_L2_16_50",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 16.50,
                     strickler = 11.5)

L2_18_90 <-  basement(model_json = "hdm_models/L2/model.json", 
                     model_new = "hdm_models/L2/model_new.json",
                     mesh_path = "hdm_models/L2/Landquart_computational-mesh_anto_depthcorr.2dm", 
                     simulation_json = "hdm_models/L2/simulation.json",
                     simulation_new = "hdm_models/L2/simulation_new.json",
                     setup_h5 = "hdm_models/L2/setup.h5",
                     results_h5 = "hdm_models/L2/results_L2_18_90.h5",
                     results_xdmf = "hdm_models/L2/results_L2_18_90",
                     results_json = "hdm_models/L2/results.json",
                     discharge = 18.90,
                     strickler = 11.5)
```

# Moesa
## M1 
```{r}
M1_0_47 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_0_47.h5",
                       results_xdmf = "hdm_models/M1/results_M1_0_47",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 0.47, 
                       strickler = 35.0)

M1_0_60 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_0_60.h5",
                       results_xdmf = "hdm_models/M1/results_M1_0_60",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 0.60, 
                       strickler = 35.0)

M1_4_00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_4_00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_4_00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 4.00, 
                       strickler = 35.0)

M1_6_00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_6_00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_6_00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 6.00, 
                       strickler = 35.0)


M1_8_00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_8_00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_8_00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 8.00, 
                       strickler = 35.0)

M1_10_00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_10_00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_10_00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 10.00, 
                       strickler = 35.0)

M1_12_00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_12_00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_12_00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 12.00, 
                       strickler = 35.0)

M1_14_00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_14_00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_14_00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 14.00, 
                       strickler = 35.0)

M1_16_00 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_16_00.h5",
                       results_xdmf = "hdm_models/M1/results_M1_16_00",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 16.00, 
                       strickler = 35.0)

M1_18_84 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_18_84.h5",
                       results_xdmf = "hdm_models/M1/results_M1_18_84",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 16.00, 
                       strickler = 35.0)


M1_22_84 <-    basement(model_json = "hdm_models/M1/model.json",  
                       model_new = "hdm_models/M1/model_new.json",
                       mesh_path = "hdm_models/M1/moesa_mzb_uebersicht_computational-mesh2.2dm", 
                       simulation_json = "hdm_models/M1/simulation.json",
                       simulation_new = "hdm_models/M1/simulation_new.json",
                       setup_h5 = "hdm_models/M1/setup.h5",
                       results_h5 = "hdm_models/M1/results_M1_22_84.h5",
                       results_xdmf = "hdm_models/M1/results_M1_22_84",
                       results_json = "hdm_models/M1/results.json",
                       discharge = 22.84, 
                       strickler = 35.0)
```

# Sitter
## S1
```{r}
S1_2_00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_2_00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_2_00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 2.00, 
                    strickler = 33.0)

S1_3_70 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_3_70.h5",
                    results_xdmf = "hdm_models/S1/results_S1_3_70", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 3.70, 
                    strickler = 33.0)

S1_6_50 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_6_50.h5",
                    results_xdmf = "hdm_models/S1/results_S1_6_50", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 6.50, 
                    strickler = 33.0)

S1_8_50 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_8_50.h5",
                    results_xdmf = "hdm_models/S1/results_S1_8_50", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 8.50, 
                    strickler = 33.0)

S1_10_68 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_10_68.h5",
                    results_xdmf = "hdm_models/S1/results_S1_10_68", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 10.68, 
                    strickler = 33.0)

S1_13_00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_13_00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_13_00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 13.00, 
                    strickler = 33.0)

S1_15_00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_15_00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_15_00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 15.00, 
                    strickler = 33.0)

S1_18_00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_18_00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_18_00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 18.00, 
                    strickler = 33.0)

S1_20_00 <- basement(model_json = "hdm_models/S1/model.json",  
                    model_new = "hdm_models/S1/model_new.json",
                    mesh_path = "hdm_models/S1/S1_mesh_computational-mesh1.2dm", 
                    simulation_json = "hdm_models/S1/simulation.json",
                    simulation_new = "hdm_models/S1/simulation_new.json",
                    setup_h5 = "hdm_models/S1/setup.h5", 
                    results_h5 = "hdm_models/S1/results_S1_20_00.h5",
                    results_xdmf = "hdm_models/S1/results_S1_20_00", 
                    results_json = "hdm_models/S1/results.json",
                    discharge = 20.00, 
                    strickler = 33.0)
```

## S2
```{r}
S2_2_00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_2_00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_2_00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 2.00, 
                    strickler = 36.0)

S2_3_20 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_3_20.h5",
                    results_xdmf = "hdm_models/S2/results_S2_3_20",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 3.20, 
                    strickler = 36.0)

S2_6_50 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_6_50.h5",
                    results_xdmf = "hdm_models/S2/results_S2_6_50",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 6.50, 
                    strickler = 36.0)

S2_8_50 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_8_50.h5",
                    results_xdmf = "hdm_models/S2/results_S2_8_50",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 8.50, 
                    strickler = 36.0)

S2_10_93 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_10_93.h5",
                    results_xdmf = "hdm_models/S2/results_S2_10_93",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 10.93, 
                    strickler = 36.0)

S2_11_40 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_11_40.h5",
                    results_xdmf = "hdm_models/S2/results_S2_11_40",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 11.40, 
                    strickler = 36.0)

S2_13_00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_13_00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_13_00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 13.00, 
                    strickler = 36.0)

S2_15_00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_15_00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_15_00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 15.00, 
                    strickler = 36.0)

S2_18_00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_18_00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_18_00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 18.00, 
                    strickler = 36.0)
       
S2_20_00 <- basement(model_json = "hdm_models/S2/model.json", 
                    model_new = "hdm_models/S2/model_new.json",
                    mesh_path = "hdm_models/S2/computational-mesh-7-290323.2dm", 
                    simulation_json = "hdm_models/S2/simulation.json",
                    simulation_new = "hdm_models/S2/simulation_new.json",
                    setup_h5 = "hdm_models/S2/setup.h5",
                    results_h5 = "hdm_models/S2/results_S2_20_00.h5",
                    results_xdmf = "hdm_models/S2/results_S2_20_00",
                    results_json = "hdm_models/S2/results.json",
                    discharge = 10.00, 
                    strickler = 36.0)
```

# Thur
## TH4
```{r}
TH4_11_45 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_11_45.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_11_45",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 11.45, 
                      strickler = 42.0)

TH4_15_00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_15_00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_15_00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 15.00, 
                      strickler = 42.0)

TH4_18_00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_18_00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_18_00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 18.00, 
                      strickler = 42.0)

TH4_19_96 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_19_96.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_19_96",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 19.96, 
                      strickler = 42.0)

TH4_22_50 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_22_50.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_22_50",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 22.50, 
                      strickler = 42.0)

TH4_25_00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_25_00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_25_00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 25.00, 
                      strickler = 42.0)

TH4_27_00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_27_00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_27_00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 27.00, 
                      strickler = 42.0)

TH4_30_00 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_30_00.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_30_00",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 30.00, 
                      strickler = 42.0)

TH4_32_93 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_32_93.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_32_93",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 32.93, 
                      strickler = 42.0)

TH4_36_30 <- basement(model_json = "hdm_models/TH4/model.json",
                      model_new = "hdm_models/TH4/model_new.json",
                      mesh_path = "hdm_models/TH4/th4_uebersicht_computational-mesh4.2dm", 
                      simulation_json = "hdm_models/TH4/simulation.json",
                      simulation_new = "hdm_models/TH4/simulation_new.json",
                      setup_h5 = "hdm_models/TH4/setup.h5",
                      results_h5 = "hdm_models/TH4/results_TH4_36_30.h5",
                      results_xdmf = "hdm_models/TH4/results_TH4_36_30",
                      results_json = "hdm_models/TH4/results.json", 
                      discharge = 36.30, 
                      strickler = 42.0)
```

# Vorderrhein
## VR3
```{r}
VR3_2_90 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_2_90.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_2_90",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 2.90, 
                     strickler = 35.0)

VR3_6_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_6_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_6_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 6.00, 
                     strickler = 35.0)

VR3_9_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_9_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_9_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 9.00, 
                     strickler = 35.0)

VR3_12_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_12_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_12_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 12.00, 
                     strickler = 35.0)

VR3_15_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_15_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_15_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 15.00, 
                     strickler = 35.0)

VR3_18_80 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_18_80.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_18_80",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 18.80, 
                     strickler = 35.0)

VR3_22_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_22_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_22_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 22.00, 
                     strickler = 35.0)

VR3_25_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_25_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_25_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 25.00, 
                     strickler = 35.0)

VR3_28_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_28_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_28_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 28.00, 
                     strickler = 35.0)

VR3_31_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_31_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_31_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 31.00, 
                     strickler = 35.0)

VR3_34_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_34_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_34_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 34.00, 
                     strickler = 35.0)

VR3_37_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_37_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_37_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 37.00, 
                     strickler = 35.0)

VR3_40_10 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_40_10.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_40_10",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 40.10, 
                     strickler = 35.0)

VR3_43_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_43_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_43_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 43.00, 
                     strickler = 35.0)

VR3_46_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_46_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_46_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 46.00, 
                     strickler = 35.0)

VR3_48_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_48_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_48_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 48.00, 
                     strickler = 35.0)

VR3_50_00 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_50_00.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_50_00",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 50.00, 
                     strickler = 35.0)

VR3_52_90 <- basement(model_json = "hdm_models/VR3/model.json", 
                     model_new = "hdm_models/VR3/model_new.json",
                     mesh_path = "hdm_models/VR3/VR_computational-mesh_3.2dm", 
                     simulation_json = "hdm_models/VR3/simulation.json", 
                     simulation_new = "hdm_models/VR3/simulation_new.json",
                     setup_h5 = "hdm_models/VR3/setup.h5",
                     results_h5 = "hdm_models/VR3/results_VR3_52_90.h5",
                     results_xdmf = "hdm_models/VR3/results_VR3_52_90",
                     results_json = "hdm_models/VR3/results.json",
                     discharge = 52.90, 
                     strickler = 35.0)
```


